-- Copyright (c) 2024 liudepei. All Rights Reserved.
-- create at 2024/03/15 13:42:54 Friday

local M = {}

local start_time = vim.fn.reltime()

local wk = require 'which-key'

local r = wk.register

r {
  ['<F9>'] = { name = '+my.box.yank', },
}

r {
  ['<F9><F9>']  = { function() require 'config.my.box'.yank_show() end, 'my.box.yank: show all', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9>a']     = { function() require 'config.my.box'.yank('a', 'n', 'w') end, 'my.box.yank: <cword> to a', mode = { 'n', }, silent = true, },
  ['<F9>b']     = { function() require 'config.my.box'.yank('b', 'n', 'w') end, 'my.box.yank: <cword> to b', mode = { 'n', }, silent = true, },
  ['<F9>c']     = { function() require 'config.my.box'.yank('c', 'n', 'w') end, 'my.box.yank: <cword> to c', mode = { 'n', }, silent = true, },
  ['<F9>d']     = { function() require 'config.my.box'.yank('d', 'n', 'w') end, 'my.box.yank: <cword> to d', mode = { 'n', }, silent = true, },
  ['<F9>e']     = { function() require 'config.my.box'.yank('e', 'n', 'w') end, 'my.box.yank: <cword> to e', mode = { 'n', }, silent = true, },
  ['<F9>f']     = { function() require 'config.my.box'.yank('f', 'n', 'w') end, 'my.box.yank: <cword> to f', mode = { 'n', }, silent = true, },
  ['<F9>g']     = { function() require 'config.my.box'.yank('g', 'n', 'w') end, 'my.box.yank: <cword> to g', mode = { 'n', }, silent = true, },
  ['<F9>h']     = { function() require 'config.my.box'.yank('h', 'n', 'w') end, 'my.box.yank: <cword> to h', mode = { 'n', }, silent = true, },
  ['<F9>i']     = { function() require 'config.my.box'.yank('i', 'n', 'w') end, 'my.box.yank: <cword> to i', mode = { 'n', }, silent = true, },
  ['<F9>j']     = { function() require 'config.my.box'.yank('j', 'n', 'w') end, 'my.box.yank: <cword> to j', mode = { 'n', }, silent = true, },
  ['<F9>k']     = { function() require 'config.my.box'.yank('k', 'n', 'w') end, 'my.box.yank: <cword> to k', mode = { 'n', }, silent = true, },
  ['<F9>l']     = { function() require 'config.my.box'.yank('l', 'n', 'w') end, 'my.box.yank: <cword> to l', mode = { 'n', }, silent = true, },
  ['<F9>m']     = { function() require 'config.my.box'.yank('m', 'n', 'w') end, 'my.box.yank: <cword> to m', mode = { 'n', }, silent = true, },
  ['<F9>n']     = { function() require 'config.my.box'.yank('n', 'n', 'w') end, 'my.box.yank: <cword> to n', mode = { 'n', }, silent = true, },
  ['<F9>o']     = { function() require 'config.my.box'.yank('o', 'n', 'w') end, 'my.box.yank: <cword> to o', mode = { 'n', }, silent = true, },
  ['<F9>p']     = { function() require 'config.my.box'.yank('p', 'n', 'w') end, 'my.box.yank: <cword> to p', mode = { 'n', }, silent = true, },
  ['<F9>q']     = { function() require 'config.my.box'.yank('q', 'n', 'w') end, 'my.box.yank: <cword> to q', mode = { 'n', }, silent = true, },
  ['<F9>r']     = { function() require 'config.my.box'.yank('r', 'n', 'w') end, 'my.box.yank: <cword> to r', mode = { 'n', }, silent = true, },
  ['<F9>s']     = { function() require 'config.my.box'.yank('s', 'n', 'w') end, 'my.box.yank: <cword> to s', mode = { 'n', }, silent = true, },
  ['<F9>t']     = { function() require 'config.my.box'.yank('t', 'n', 'w') end, 'my.box.yank: <cword> to t', mode = { 'n', }, silent = true, },
  ['<F9>u']     = { function() require 'config.my.box'.yank('u', 'n', 'w') end, 'my.box.yank: <cword> to u', mode = { 'n', }, silent = true, },
  ['<F9>v']     = { function() require 'config.my.box'.yank('v', 'n', 'w') end, 'my.box.yank: <cword> to v', mode = { 'n', }, silent = true, },
  ['<F9>w']     = { function() require 'config.my.box'.yank('w', 'n', 'w') end, 'my.box.yank: <cword> to w', mode = { 'n', }, silent = true, },
  ['<F9>x']     = { function() require 'config.my.box'.yank('x', 'n', 'w') end, 'my.box.yank: <cword> to x', mode = { 'n', }, silent = true, },
  ['<F9>y']     = { function() require 'config.my.box'.yank('y', 'n', 'w') end, 'my.box.yank: <cword> to y', mode = { 'n', }, silent = true, },
  ['<F9>z']     = { function() require 'config.my.box'.yank('z', 'n', 'w') end, 'my.box.yank: <cword> to z', mode = { 'n', }, silent = true, },
  ['<F9>,']     = { function() require 'config.my.box'.yank(',', 'n', 'w') end, 'my.box.yank: <cword> to ,', mode = { 'n', }, silent = true, },
  ['<F9>.']     = { function() require 'config.my.box'.yank('.', 'n', 'w') end, 'my.box.yank: <cword> to .', mode = { 'n', }, silent = true, },
  ['<F9>/']     = { function() require 'config.my.box'.yank('/', 'n', 'w') end, 'my.box.yank: <cword> to /', mode = { 'n', }, silent = true, },
  ['<F9>;']     = { function() require 'config.my.box'.yank(';', 'n', 'w') end, 'my.box.yank: <cword> to ;', mode = { 'n', }, silent = true, },
  ["<F9>'"]     = { function() require 'config.my.box'.yank("'", 'n', 'w') end, "my.box.yank: <cword> to '", mode = { 'n', }, silent = true, },
  ['<F9>[']     = { function() require 'config.my.box'.yank('[', 'n', 'w') end, 'my.box.yank: <cword> to [', mode = { 'n', }, silent = true, },
  ['<F9>]']     = { function() require 'config.my.box'.yank(']', 'n', 'w') end, 'my.box.yank: <cword> to ]', mode = { 'n', }, silent = true, },
  ['<F9><a-a>'] = { function() require 'config.my.box'.yank('a', 'n', 'W') end, 'my.box.yank: <cWORD> to a', mode = { 'n', }, silent = true, },
  ['<F9><a-b>'] = { function() require 'config.my.box'.yank('b', 'n', 'W') end, 'my.box.yank: <cWORD> to b', mode = { 'n', }, silent = true, },
  ['<F9><a-c>'] = { function() require 'config.my.box'.yank('c', 'n', 'W') end, 'my.box.yank: <cWORD> to c', mode = { 'n', }, silent = true, },
  ['<F9><a-d>'] = { function() require 'config.my.box'.yank('d', 'n', 'W') end, 'my.box.yank: <cWORD> to d', mode = { 'n', }, silent = true, },
  ['<F9><a-e>'] = { function() require 'config.my.box'.yank('e', 'n', 'W') end, 'my.box.yank: <cWORD> to e', mode = { 'n', }, silent = true, },
  ['<F9><a-f>'] = { function() require 'config.my.box'.yank('f', 'n', 'W') end, 'my.box.yank: <cWORD> to f', mode = { 'n', }, silent = true, },
  ['<F9><a-g>'] = { function() require 'config.my.box'.yank('g', 'n', 'W') end, 'my.box.yank: <cWORD> to g', mode = { 'n', }, silent = true, },
  ['<F9><a-h>'] = { function() require 'config.my.box'.yank('h', 'n', 'W') end, 'my.box.yank: <cWORD> to h', mode = { 'n', }, silent = true, },
  ['<F9><a-i>'] = { function() require 'config.my.box'.yank('i', 'n', 'W') end, 'my.box.yank: <cWORD> to i', mode = { 'n', }, silent = true, },
  ['<F9><a-j>'] = { function() require 'config.my.box'.yank('j', 'n', 'W') end, 'my.box.yank: <cWORD> to j', mode = { 'n', }, silent = true, },
  ['<F9><a-k>'] = { function() require 'config.my.box'.yank('k', 'n', 'W') end, 'my.box.yank: <cWORD> to k', mode = { 'n', }, silent = true, },
  ['<F9><a-l>'] = { function() require 'config.my.box'.yank('l', 'n', 'W') end, 'my.box.yank: <cWORD> to l', mode = { 'n', }, silent = true, },
  ['<F9><a-m>'] = { function() require 'config.my.box'.yank('m', 'n', 'W') end, 'my.box.yank: <cWORD> to m', mode = { 'n', }, silent = true, },
  ['<F9><a-n>'] = { function() require 'config.my.box'.yank('n', 'n', 'W') end, 'my.box.yank: <cWORD> to n', mode = { 'n', }, silent = true, },
  ['<F9><a-o>'] = { function() require 'config.my.box'.yank('o', 'n', 'W') end, 'my.box.yank: <cWORD> to o', mode = { 'n', }, silent = true, },
  ['<F9><a-p>'] = { function() require 'config.my.box'.yank('p', 'n', 'W') end, 'my.box.yank: <cWORD> to p', mode = { 'n', }, silent = true, },
  ['<F9><a-q>'] = { function() require 'config.my.box'.yank('q', 'n', 'W') end, 'my.box.yank: <cWORD> to q', mode = { 'n', }, silent = true, },
  ['<F9><a-r>'] = { function() require 'config.my.box'.yank('r', 'n', 'W') end, 'my.box.yank: <cWORD> to r', mode = { 'n', }, silent = true, },
  ['<F9><a-s>'] = { function() require 'config.my.box'.yank('s', 'n', 'W') end, 'my.box.yank: <cWORD> to s', mode = { 'n', }, silent = true, },
  ['<F9><a-t>'] = { function() require 'config.my.box'.yank('t', 'n', 'W') end, 'my.box.yank: <cWORD> to t', mode = { 'n', }, silent = true, },
  ['<F9><a-u>'] = { function() require 'config.my.box'.yank('u', 'n', 'W') end, 'my.box.yank: <cWORD> to u', mode = { 'n', }, silent = true, },
  ['<F9><a-v>'] = { function() require 'config.my.box'.yank('v', 'n', 'W') end, 'my.box.yank: <cWORD> to v', mode = { 'n', }, silent = true, },
  ['<F9><a-w>'] = { function() require 'config.my.box'.yank('w', 'n', 'W') end, 'my.box.yank: <cWORD> to w', mode = { 'n', }, silent = true, },
  ['<F9><a-x>'] = { function() require 'config.my.box'.yank('x', 'n', 'W') end, 'my.box.yank: <cWORD> to x', mode = { 'n', }, silent = true, },
  ['<F9><a-y>'] = { function() require 'config.my.box'.yank('y', 'n', 'W') end, 'my.box.yank: <cWORD> to y', mode = { 'n', }, silent = true, },
  ['<F9><a-z>'] = { function() require 'config.my.box'.yank('z', 'n', 'W') end, 'my.box.yank: <cWORD> to z', mode = { 'n', }, silent = true, },
  ['<F9><a-,>'] = { function() require 'config.my.box'.yank(',', 'n', 'W') end, 'my.box.yank: <cWORD> to ,', mode = { 'n', }, silent = true, },
  ['<F9><a-.>'] = { function() require 'config.my.box'.yank('.', 'n', 'W') end, 'my.box.yank: <cWORD> to .', mode = { 'n', }, silent = true, },
  ['<F9><a-/>'] = { function() require 'config.my.box'.yank('/', 'n', 'W') end, 'my.box.yank: <cWORD> to /', mode = { 'n', }, silent = true, },
  ['<F9><a-;>'] = { function() require 'config.my.box'.yank(';', 'n', 'W') end, 'my.box.yank: <cWORD> to ;', mode = { 'n', }, silent = true, },
  ["<F9><a-'>"] = { function() require 'config.my.box'.yank("'", 'n', 'W') end, "my.box.yank: <cWORD> to '", mode = { 'n', }, silent = true, },
  ['<F9><a-[>'] = { function() require 'config.my.box'.yank('[', 'n', 'W') end, 'my.box.yank: <cWORD> to [', mode = { 'n', }, silent = true, },
  ['<F9><a-]>'] = { function() require 'config.my.box'.yank(']', 'n', 'W') end, 'my.box.yank: <cWORD> to ]', mode = { 'n', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.box'.yank('a', 'v') end, 'my.box.yank: sel to a', mode = { 'v', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.box'.yank('b', 'v') end, 'my.box.yank: sel to b', mode = { 'v', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.box'.yank('c', 'v') end, 'my.box.yank: sel to c', mode = { 'v', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.box'.yank('d', 'v') end, 'my.box.yank: sel to d', mode = { 'v', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.box'.yank('e', 'v') end, 'my.box.yank: sel to e', mode = { 'v', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.box'.yank('f', 'v') end, 'my.box.yank: sel to f', mode = { 'v', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.box'.yank('g', 'v') end, 'my.box.yank: sel to g', mode = { 'v', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.box'.yank('h', 'v') end, 'my.box.yank: sel to h', mode = { 'v', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.box'.yank('i', 'v') end, 'my.box.yank: sel to i', mode = { 'v', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.box'.yank('j', 'v') end, 'my.box.yank: sel to j', mode = { 'v', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.box'.yank('k', 'v') end, 'my.box.yank: sel to k', mode = { 'v', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.box'.yank('l', 'v') end, 'my.box.yank: sel to l', mode = { 'v', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.box'.yank('m', 'v') end, 'my.box.yank: sel to m', mode = { 'v', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.box'.yank('n', 'v') end, 'my.box.yank: sel to n', mode = { 'v', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.box'.yank('o', 'v') end, 'my.box.yank: sel to o', mode = { 'v', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.box'.yank('p', 'v') end, 'my.box.yank: sel to p', mode = { 'v', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.box'.yank('q', 'v') end, 'my.box.yank: sel to q', mode = { 'v', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.box'.yank('r', 'v') end, 'my.box.yank: sel to r', mode = { 'v', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.box'.yank('s', 'v') end, 'my.box.yank: sel to s', mode = { 'v', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.box'.yank('t', 'v') end, 'my.box.yank: sel to t', mode = { 'v', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.box'.yank('u', 'v') end, 'my.box.yank: sel to u', mode = { 'v', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.box'.yank('v', 'v') end, 'my.box.yank: sel to v', mode = { 'v', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.box'.yank('w', 'v') end, 'my.box.yank: sel to w', mode = { 'v', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.box'.yank('x', 'v') end, 'my.box.yank: sel to x', mode = { 'v', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.box'.yank('y', 'v') end, 'my.box.yank: sel to y', mode = { 'v', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.box'.yank('z', 'v') end, 'my.box.yank: sel to z', mode = { 'v', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.box'.yank(',', 'v') end, 'my.box.yank: sel to ,', mode = { 'v', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.box'.yank('.', 'v') end, 'my.box.yank: sel to .', mode = { 'v', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.box'.yank('/', 'v') end, 'my.box.yank: sel to /', mode = { 'v', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.box'.yank(';', 'v') end, 'my.box.yank: sel to ;', mode = { 'v', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.box'.yank("'", 'v') end, "my.box.yank: sel to '", mode = { 'v', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.box'.yank('[', 'v') end, 'my.box.yank: sel to [', mode = { 'v', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.box'.yank(']', 'v') end, 'my.box.yank: sel to ]', mode = { 'v', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.box'.paste('a', 'i') end, 'my.box.paste: paste from a', mode = { 'i', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.box'.paste('b', 'i') end, 'my.box.paste: paste from b', mode = { 'i', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.box'.paste('c', 'i') end, 'my.box.paste: paste from c', mode = { 'i', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.box'.paste('d', 'i') end, 'my.box.paste: paste from d', mode = { 'i', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.box'.paste('e', 'i') end, 'my.box.paste: paste from e', mode = { 'i', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.box'.paste('f', 'i') end, 'my.box.paste: paste from f', mode = { 'i', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.box'.paste('g', 'i') end, 'my.box.paste: paste from g', mode = { 'i', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.box'.paste('h', 'i') end, 'my.box.paste: paste from h', mode = { 'i', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.box'.paste('i', 'i') end, 'my.box.paste: paste from i', mode = { 'i', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.box'.paste('j', 'i') end, 'my.box.paste: paste from j', mode = { 'i', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.box'.paste('k', 'i') end, 'my.box.paste: paste from k', mode = { 'i', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.box'.paste('l', 'i') end, 'my.box.paste: paste from l', mode = { 'i', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.box'.paste('m', 'i') end, 'my.box.paste: paste from m', mode = { 'i', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.box'.paste('n', 'i') end, 'my.box.paste: paste from n', mode = { 'i', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.box'.paste('o', 'i') end, 'my.box.paste: paste from o', mode = { 'i', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.box'.paste('p', 'i') end, 'my.box.paste: paste from p', mode = { 'i', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.box'.paste('q', 'i') end, 'my.box.paste: paste from q', mode = { 'i', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.box'.paste('r', 'i') end, 'my.box.paste: paste from r', mode = { 'i', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.box'.paste('s', 'i') end, 'my.box.paste: paste from s', mode = { 'i', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.box'.paste('t', 'i') end, 'my.box.paste: paste from t', mode = { 'i', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.box'.paste('u', 'i') end, 'my.box.paste: paste from u', mode = { 'i', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.box'.paste('v', 'i') end, 'my.box.paste: paste from v', mode = { 'i', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.box'.paste('w', 'i') end, 'my.box.paste: paste from w', mode = { 'i', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.box'.paste('x', 'i') end, 'my.box.paste: paste from x', mode = { 'i', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.box'.paste('y', 'i') end, 'my.box.paste: paste from y', mode = { 'i', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.box'.paste('z', 'i') end, 'my.box.paste: paste from z', mode = { 'i', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.box'.paste(',', 'i') end, 'my.box.paste: paste from ,', mode = { 'i', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.box'.paste('.', 'i') end, 'my.box.paste: paste from .', mode = { 'i', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.box'.paste('/', 'i') end, 'my.box.paste: paste from /', mode = { 'i', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.box'.paste(';', 'i') end, 'my.box.paste: paste from ;', mode = { 'i', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.box'.paste("'", 'i') end, "my.box.paste: paste from '", mode = { 'i', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.box'.paste('[', 'i') end, 'my.box.paste: paste from [', mode = { 'i', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.box'.paste(']', 'i') end, 'my.box.paste: paste from ]', mode = { 'i', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.box'.paste('a', 'c') end, 'my.box.paste: paste from a', mode = { 'c', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.box'.paste('b', 'c') end, 'my.box.paste: paste from b', mode = { 'c', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.box'.paste('c', 'c') end, 'my.box.paste: paste from c', mode = { 'c', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.box'.paste('d', 'c') end, 'my.box.paste: paste from d', mode = { 'c', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.box'.paste('e', 'c') end, 'my.box.paste: paste from e', mode = { 'c', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.box'.paste('f', 'c') end, 'my.box.paste: paste from f', mode = { 'c', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.box'.paste('g', 'c') end, 'my.box.paste: paste from g', mode = { 'c', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.box'.paste('h', 'c') end, 'my.box.paste: paste from h', mode = { 'c', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.box'.paste('i', 'c') end, 'my.box.paste: paste from i', mode = { 'c', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.box'.paste('j', 'c') end, 'my.box.paste: paste from j', mode = { 'c', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.box'.paste('k', 'c') end, 'my.box.paste: paste from k', mode = { 'c', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.box'.paste('l', 'c') end, 'my.box.paste: paste from l', mode = { 'c', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.box'.paste('m', 'c') end, 'my.box.paste: paste from m', mode = { 'c', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.box'.paste('n', 'c') end, 'my.box.paste: paste from n', mode = { 'c', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.box'.paste('o', 'c') end, 'my.box.paste: paste from o', mode = { 'c', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.box'.paste('p', 'c') end, 'my.box.paste: paste from p', mode = { 'c', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.box'.paste('q', 'c') end, 'my.box.paste: paste from q', mode = { 'c', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.box'.paste('r', 'c') end, 'my.box.paste: paste from r', mode = { 'c', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.box'.paste('s', 'c') end, 'my.box.paste: paste from s', mode = { 'c', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.box'.paste('t', 'c') end, 'my.box.paste: paste from t', mode = { 'c', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.box'.paste('u', 'c') end, 'my.box.paste: paste from u', mode = { 'c', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.box'.paste('v', 'c') end, 'my.box.paste: paste from v', mode = { 'c', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.box'.paste('w', 'c') end, 'my.box.paste: paste from w', mode = { 'c', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.box'.paste('x', 'c') end, 'my.box.paste: paste from x', mode = { 'c', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.box'.paste('y', 'c') end, 'my.box.paste: paste from y', mode = { 'c', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.box'.paste('z', 'c') end, 'my.box.paste: paste from z', mode = { 'c', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.box'.paste(',', 'c') end, 'my.box.paste: paste from ,', mode = { 'c', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.box'.paste('.', 'c') end, 'my.box.paste: paste from .', mode = { 'c', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.box'.paste('/', 'c') end, 'my.box.paste: paste from /', mode = { 'c', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.box'.paste(';', 'c') end, 'my.box.paste: paste from ;', mode = { 'c', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.box'.paste("'", 'c') end, "my.box.paste: paste from '", mode = { 'c', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.box'.paste('[', 'c') end, 'my.box.paste: paste from [', mode = { 'c', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.box'.paste(']', 'c') end, 'my.box.paste: paste from ]', mode = { 'c', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.box'.paste('a', 't') end, 'my.box.paste: paste from a', mode = { 't', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.box'.paste('b', 't') end, 'my.box.paste: paste from b', mode = { 't', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.box'.paste('c', 't') end, 'my.box.paste: paste from c', mode = { 't', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.box'.paste('d', 't') end, 'my.box.paste: paste from d', mode = { 't', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.box'.paste('e', 't') end, 'my.box.paste: paste from e', mode = { 't', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.box'.paste('f', 't') end, 'my.box.paste: paste from f', mode = { 't', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.box'.paste('g', 't') end, 'my.box.paste: paste from g', mode = { 't', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.box'.paste('h', 't') end, 'my.box.paste: paste from h', mode = { 't', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.box'.paste('i', 't') end, 'my.box.paste: paste from i', mode = { 't', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.box'.paste('j', 't') end, 'my.box.paste: paste from j', mode = { 't', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.box'.paste('k', 't') end, 'my.box.paste: paste from k', mode = { 't', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.box'.paste('l', 't') end, 'my.box.paste: paste from l', mode = { 't', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.box'.paste('m', 't') end, 'my.box.paste: paste from m', mode = { 't', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.box'.paste('n', 't') end, 'my.box.paste: paste from n', mode = { 't', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.box'.paste('o', 't') end, 'my.box.paste: paste from o', mode = { 't', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.box'.paste('p', 't') end, 'my.box.paste: paste from p', mode = { 't', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.box'.paste('q', 't') end, 'my.box.paste: paste from q', mode = { 't', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.box'.paste('r', 't') end, 'my.box.paste: paste from r', mode = { 't', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.box'.paste('s', 't') end, 'my.box.paste: paste from s', mode = { 't', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.box'.paste('t', 't') end, 'my.box.paste: paste from t', mode = { 't', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.box'.paste('u', 't') end, 'my.box.paste: paste from u', mode = { 't', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.box'.paste('v', 't') end, 'my.box.paste: paste from v', mode = { 't', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.box'.paste('w', 't') end, 'my.box.paste: paste from w', mode = { 't', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.box'.paste('x', 't') end, 'my.box.paste: paste from x', mode = { 't', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.box'.paste('y', 't') end, 'my.box.paste: paste from y', mode = { 't', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.box'.paste('z', 't') end, 'my.box.paste: paste from z', mode = { 't', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.box'.paste(',', 't') end, 'my.box.paste: paste from ,', mode = { 't', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.box'.paste('.', 't') end, 'my.box.paste: paste from .', mode = { 't', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.box'.paste('/', 't') end, 'my.box.paste: paste from /', mode = { 't', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.box'.paste(';', 't') end, 'my.box.paste: paste from ;', mode = { 't', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.box'.paste("'", 't') end, "my.box.paste: paste from '", mode = { 't', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.box'.paste('[', 't') end, 'my.box.paste: paste from [', mode = { 't', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.box'.paste(']', 't') end, 'my.box.paste: paste from ]', mode = { 't', }, silent = true, },
}

r {
  ['<F9>A'] = { function() require 'config.my.box'.paste('a', 'n') end, 'my.box.paste: paste from a', mode = { 'n', 'v', }, silent = true, },
  ['<F9>B'] = { function() require 'config.my.box'.paste('b', 'n') end, 'my.box.paste: paste from b', mode = { 'n', 'v', }, silent = true, },
  ['<F9>C'] = { function() require 'config.my.box'.paste('c', 'n') end, 'my.box.paste: paste from c', mode = { 'n', 'v', }, silent = true, },
  ['<F9>D'] = { function() require 'config.my.box'.paste('d', 'n') end, 'my.box.paste: paste from d', mode = { 'n', 'v', }, silent = true, },
  ['<F9>E'] = { function() require 'config.my.box'.paste('e', 'n') end, 'my.box.paste: paste from e', mode = { 'n', 'v', }, silent = true, },
  ['<F9>F'] = { function() require 'config.my.box'.paste('f', 'n') end, 'my.box.paste: paste from f', mode = { 'n', 'v', }, silent = true, },
  ['<F9>G'] = { function() require 'config.my.box'.paste('g', 'n') end, 'my.box.paste: paste from g', mode = { 'n', 'v', }, silent = true, },
  ['<F9>H'] = { function() require 'config.my.box'.paste('h', 'n') end, 'my.box.paste: paste from h', mode = { 'n', 'v', }, silent = true, },
  ['<F9>I'] = { function() require 'config.my.box'.paste('i', 'n') end, 'my.box.paste: paste from i', mode = { 'n', 'v', }, silent = true, },
  ['<F9>J'] = { function() require 'config.my.box'.paste('j', 'n') end, 'my.box.paste: paste from j', mode = { 'n', 'v', }, silent = true, },
  ['<F9>K'] = { function() require 'config.my.box'.paste('k', 'n') end, 'my.box.paste: paste from k', mode = { 'n', 'v', }, silent = true, },
  ['<F9>L'] = { function() require 'config.my.box'.paste('l', 'n') end, 'my.box.paste: paste from l', mode = { 'n', 'v', }, silent = true, },
  ['<F9>M'] = { function() require 'config.my.box'.paste('m', 'n') end, 'my.box.paste: paste from m', mode = { 'n', 'v', }, silent = true, },
  ['<F9>N'] = { function() require 'config.my.box'.paste('n', 'n') end, 'my.box.paste: paste from n', mode = { 'n', 'v', }, silent = true, },
  ['<F9>O'] = { function() require 'config.my.box'.paste('o', 'n') end, 'my.box.paste: paste from o', mode = { 'n', 'v', }, silent = true, },
  ['<F9>P'] = { function() require 'config.my.box'.paste('p', 'n') end, 'my.box.paste: paste from p', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Q'] = { function() require 'config.my.box'.paste('q', 'n') end, 'my.box.paste: paste from q', mode = { 'n', 'v', }, silent = true, },
  ['<F9>R'] = { function() require 'config.my.box'.paste('r', 'n') end, 'my.box.paste: paste from r', mode = { 'n', 'v', }, silent = true, },
  ['<F9>S'] = { function() require 'config.my.box'.paste('s', 'n') end, 'my.box.paste: paste from s', mode = { 'n', 'v', }, silent = true, },
  ['<F9>T'] = { function() require 'config.my.box'.paste('t', 'n') end, 'my.box.paste: paste from t', mode = { 'n', 'v', }, silent = true, },
  ['<F9>U'] = { function() require 'config.my.box'.paste('u', 'n') end, 'my.box.paste: paste from u', mode = { 'n', 'v', }, silent = true, },
  ['<F9>V'] = { function() require 'config.my.box'.paste('v', 'n') end, 'my.box.paste: paste from v', mode = { 'n', 'v', }, silent = true, },
  ['<F9>W'] = { function() require 'config.my.box'.paste('w', 'n') end, 'my.box.paste: paste from w', mode = { 'n', 'v', }, silent = true, },
  ['<F9>X'] = { function() require 'config.my.box'.paste('x', 'n') end, 'my.box.paste: paste from x', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Y'] = { function() require 'config.my.box'.paste('y', 'n') end, 'my.box.paste: paste from y', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Z'] = { function() require 'config.my.box'.paste('z', 'n') end, 'my.box.paste: paste from z', mode = { 'n', 'v', }, silent = true, },
  ['<F9><'] = { function() require 'config.my.box'.paste(',', 'n') end, 'my.box.paste: paste from ,', mode = { 'n', 'v', }, silent = true, },
  ['<F9>>'] = { function() require 'config.my.box'.paste('.', 'n') end, 'my.box.paste: paste from .', mode = { 'n', 'v', }, silent = true, },
  ['<F9>?'] = { function() require 'config.my.box'.paste('/', 'n') end, 'my.box.paste: paste from /', mode = { 'n', 'v', }, silent = true, },
  ['<F9>:'] = { function() require 'config.my.box'.paste(';', 'n') end, 'my.box.paste: paste from ;', mode = { 'n', 'v', }, silent = true, },
  ['<F9>"'] = { function() require 'config.my.box'.paste("'", 'n') end, "my.box.paste: paste from '", mode = { 'n', 'v', }, silent = true, },
  ['<F9>{'] = { function() require 'config.my.box'.paste('[', 'n') end, 'my.box.paste: paste from [', mode = { 'n', 'v', }, silent = true, },
  ['<F9>}'] = { function() require 'config.my.box'.paste(']', 'n') end, 'my.box.paste: paste from ]', mode = { 'n', 'v', }, silent = true, },
}

local end_time = vim.fn.reltimefloat(vim.fn.reltime(start_time))
local startup_time = string.format('wk.register time: %.3f ms', end_time * 1000)
print(vim.g.startup_time .. ', ' .. startup_time)

return M
