-- Copyright (c) 2024 liudepei. All Rights Reserved.
-- create at 2024/03/15 13:42:54 Friday

local M = {}

local start_time = vim.fn.reltime()

local wk = require 'which-key'

local r = wk.register

r {
  ['<F9>'] = { name = '+my.yank', },
  ['<F9><F1>'] = { name = '+my.yank.clipboard.cword', },
  ['<F9><F2>'] = { name = '+my.yank.clipboard.cWORD', },
}

r {
  ['<F9><F9>']  = { function() require 'config.my.yank'.reg_show() end, 'my.yank: show all', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9>a']     = { function() require 'config.my.yank'.yank('a', 'n', 'w') end, 'my.yank: <cword> to a', mode = { 'n', }, silent = true, },
  ['<F9>b']     = { function() require 'config.my.yank'.yank('b', 'n', 'w') end, 'my.yank: <cword> to b', mode = { 'n', }, silent = true, },
  ['<F9>c']     = { function() require 'config.my.yank'.yank('c', 'n', 'w') end, 'my.yank: <cword> to c', mode = { 'n', }, silent = true, },
  ['<F9>d']     = { function() require 'config.my.yank'.yank('d', 'n', 'w') end, 'my.yank: <cword> to d', mode = { 'n', }, silent = true, },
  ['<F9>e']     = { function() require 'config.my.yank'.yank('e', 'n', 'w') end, 'my.yank: <cword> to e', mode = { 'n', }, silent = true, },
  ['<F9>f']     = { function() require 'config.my.yank'.yank('f', 'n', 'w') end, 'my.yank: <cword> to f', mode = { 'n', }, silent = true, },
  ['<F9>g']     = { function() require 'config.my.yank'.yank('g', 'n', 'w') end, 'my.yank: <cword> to g', mode = { 'n', }, silent = true, },
  ['<F9>h']     = { function() require 'config.my.yank'.yank('h', 'n', 'w') end, 'my.yank: <cword> to h', mode = { 'n', }, silent = true, },
  ['<F9>i']     = { function() require 'config.my.yank'.yank('i', 'n', 'w') end, 'my.yank: <cword> to i', mode = { 'n', }, silent = true, },
  ['<F9>j']     = { function() require 'config.my.yank'.yank('j', 'n', 'w') end, 'my.yank: <cword> to j', mode = { 'n', }, silent = true, },
  ['<F9>k']     = { function() require 'config.my.yank'.yank('k', 'n', 'w') end, 'my.yank: <cword> to k', mode = { 'n', }, silent = true, },
  ['<F9>l']     = { function() require 'config.my.yank'.yank('l', 'n', 'w') end, 'my.yank: <cword> to l', mode = { 'n', }, silent = true, },
  ['<F9>m']     = { function() require 'config.my.yank'.yank('m', 'n', 'w') end, 'my.yank: <cword> to m', mode = { 'n', }, silent = true, },
  ['<F9>n']     = { function() require 'config.my.yank'.yank('n', 'n', 'w') end, 'my.yank: <cword> to n', mode = { 'n', }, silent = true, },
  ['<F9>o']     = { function() require 'config.my.yank'.yank('o', 'n', 'w') end, 'my.yank: <cword> to o', mode = { 'n', }, silent = true, },
  ['<F9>p']     = { function() require 'config.my.yank'.yank('p', 'n', 'w') end, 'my.yank: <cword> to p', mode = { 'n', }, silent = true, },
  ['<F9>q']     = { function() require 'config.my.yank'.yank('q', 'n', 'w') end, 'my.yank: <cword> to q', mode = { 'n', }, silent = true, },
  ['<F9>r']     = { function() require 'config.my.yank'.yank('r', 'n', 'w') end, 'my.yank: <cword> to r', mode = { 'n', }, silent = true, },
  ['<F9>s']     = { function() require 'config.my.yank'.yank('s', 'n', 'w') end, 'my.yank: <cword> to s', mode = { 'n', }, silent = true, },
  ['<F9>t']     = { function() require 'config.my.yank'.yank('t', 'n', 'w') end, 'my.yank: <cword> to t', mode = { 'n', }, silent = true, },
  ['<F9>u']     = { function() require 'config.my.yank'.yank('u', 'n', 'w') end, 'my.yank: <cword> to u', mode = { 'n', }, silent = true, },
  ['<F9>v']     = { function() require 'config.my.yank'.yank('v', 'n', 'w') end, 'my.yank: <cword> to v', mode = { 'n', }, silent = true, },
  ['<F9>w']     = { function() require 'config.my.yank'.yank('w', 'n', 'w') end, 'my.yank: <cword> to w', mode = { 'n', }, silent = true, },
  ['<F9>x']     = { function() require 'config.my.yank'.yank('x', 'n', 'w') end, 'my.yank: <cword> to x', mode = { 'n', }, silent = true, },
  ['<F9>y']     = { function() require 'config.my.yank'.yank('y', 'n', 'w') end, 'my.yank: <cword> to y', mode = { 'n', }, silent = true, },
  ['<F9>z']     = { function() require 'config.my.yank'.yank('z', 'n', 'w') end, 'my.yank: <cword> to z', mode = { 'n', }, silent = true, },
  ['<F9>,']     = { function() require 'config.my.yank'.yank(',', 'n', 'w') end, 'my.yank: <cword> to ,', mode = { 'n', }, silent = true, },
  ['<F9>.']     = { function() require 'config.my.yank'.yank('.', 'n', 'w') end, 'my.yank: <cword> to .', mode = { 'n', }, silent = true, },
  ['<F9>/']     = { function() require 'config.my.yank'.yank('/', 'n', 'w') end, 'my.yank: <cword> to /', mode = { 'n', }, silent = true, },
  ['<F9>;']     = { function() require 'config.my.yank'.yank(';', 'n', 'w') end, 'my.yank: <cword> to ;', mode = { 'n', }, silent = true, },
  ["<F9>'"]     = { function() require 'config.my.yank'.yank("'", 'n', 'w') end, "my.yank: <cword> to '", mode = { 'n', }, silent = true, },
  ['<F9>[']     = { function() require 'config.my.yank'.yank('[', 'n', 'w') end, 'my.yank: <cword> to [', mode = { 'n', }, silent = true, },
  ['<F9>]']     = { function() require 'config.my.yank'.yank(']', 'n', 'w') end, 'my.yank: <cword> to ]', mode = { 'n', }, silent = true, },
  ['<F9><a-a>'] = { function() require 'config.my.yank'.yank('a', 'n', 'W') end, 'my.yank: <cWORD> to a', mode = { 'n', }, silent = true, },
  ['<F9><a-b>'] = { function() require 'config.my.yank'.yank('b', 'n', 'W') end, 'my.yank: <cWORD> to b', mode = { 'n', }, silent = true, },
  ['<F9><a-c>'] = { function() require 'config.my.yank'.yank('c', 'n', 'W') end, 'my.yank: <cWORD> to c', mode = { 'n', }, silent = true, },
  ['<F9><a-d>'] = { function() require 'config.my.yank'.yank('d', 'n', 'W') end, 'my.yank: <cWORD> to d', mode = { 'n', }, silent = true, },
  ['<F9><a-e>'] = { function() require 'config.my.yank'.yank('e', 'n', 'W') end, 'my.yank: <cWORD> to e', mode = { 'n', }, silent = true, },
  ['<F9><a-f>'] = { function() require 'config.my.yank'.yank('f', 'n', 'W') end, 'my.yank: <cWORD> to f', mode = { 'n', }, silent = true, },
  ['<F9><a-g>'] = { function() require 'config.my.yank'.yank('g', 'n', 'W') end, 'my.yank: <cWORD> to g', mode = { 'n', }, silent = true, },
  ['<F9><a-h>'] = { function() require 'config.my.yank'.yank('h', 'n', 'W') end, 'my.yank: <cWORD> to h', mode = { 'n', }, silent = true, },
  ['<F9><a-i>'] = { function() require 'config.my.yank'.yank('i', 'n', 'W') end, 'my.yank: <cWORD> to i', mode = { 'n', }, silent = true, },
  ['<F9><a-j>'] = { function() require 'config.my.yank'.yank('j', 'n', 'W') end, 'my.yank: <cWORD> to j', mode = { 'n', }, silent = true, },
  ['<F9><a-k>'] = { function() require 'config.my.yank'.yank('k', 'n', 'W') end, 'my.yank: <cWORD> to k', mode = { 'n', }, silent = true, },
  ['<F9><a-l>'] = { function() require 'config.my.yank'.yank('l', 'n', 'W') end, 'my.yank: <cWORD> to l', mode = { 'n', }, silent = true, },
  ['<F9><a-m>'] = { function() require 'config.my.yank'.yank('m', 'n', 'W') end, 'my.yank: <cWORD> to m', mode = { 'n', }, silent = true, },
  ['<F9><a-n>'] = { function() require 'config.my.yank'.yank('n', 'n', 'W') end, 'my.yank: <cWORD> to n', mode = { 'n', }, silent = true, },
  ['<F9><a-o>'] = { function() require 'config.my.yank'.yank('o', 'n', 'W') end, 'my.yank: <cWORD> to o', mode = { 'n', }, silent = true, },
  ['<F9><a-p>'] = { function() require 'config.my.yank'.yank('p', 'n', 'W') end, 'my.yank: <cWORD> to p', mode = { 'n', }, silent = true, },
  ['<F9><a-q>'] = { function() require 'config.my.yank'.yank('q', 'n', 'W') end, 'my.yank: <cWORD> to q', mode = { 'n', }, silent = true, },
  ['<F9><a-r>'] = { function() require 'config.my.yank'.yank('r', 'n', 'W') end, 'my.yank: <cWORD> to r', mode = { 'n', }, silent = true, },
  ['<F9><a-s>'] = { function() require 'config.my.yank'.yank('s', 'n', 'W') end, 'my.yank: <cWORD> to s', mode = { 'n', }, silent = true, },
  ['<F9><a-t>'] = { function() require 'config.my.yank'.yank('t', 'n', 'W') end, 'my.yank: <cWORD> to t', mode = { 'n', }, silent = true, },
  ['<F9><a-u>'] = { function() require 'config.my.yank'.yank('u', 'n', 'W') end, 'my.yank: <cWORD> to u', mode = { 'n', }, silent = true, },
  ['<F9><a-v>'] = { function() require 'config.my.yank'.yank('v', 'n', 'W') end, 'my.yank: <cWORD> to v', mode = { 'n', }, silent = true, },
  ['<F9><a-w>'] = { function() require 'config.my.yank'.yank('w', 'n', 'W') end, 'my.yank: <cWORD> to w', mode = { 'n', }, silent = true, },
  ['<F9><a-x>'] = { function() require 'config.my.yank'.yank('x', 'n', 'W') end, 'my.yank: <cWORD> to x', mode = { 'n', }, silent = true, },
  ['<F9><a-y>'] = { function() require 'config.my.yank'.yank('y', 'n', 'W') end, 'my.yank: <cWORD> to y', mode = { 'n', }, silent = true, },
  ['<F9><a-z>'] = { function() require 'config.my.yank'.yank('z', 'n', 'W') end, 'my.yank: <cWORD> to z', mode = { 'n', }, silent = true, },
  ['<F9><a-,>'] = { function() require 'config.my.yank'.yank(',', 'n', 'W') end, 'my.yank: <cWORD> to ,', mode = { 'n', }, silent = true, },
  ['<F9><a-.>'] = { function() require 'config.my.yank'.yank('.', 'n', 'W') end, 'my.yank: <cWORD> to .', mode = { 'n', }, silent = true, },
  ['<F9><a-/>'] = { function() require 'config.my.yank'.yank('/', 'n', 'W') end, 'my.yank: <cWORD> to /', mode = { 'n', }, silent = true, },
  ['<F9><a-;>'] = { function() require 'config.my.yank'.yank(';', 'n', 'W') end, 'my.yank: <cWORD> to ;', mode = { 'n', }, silent = true, },
  ["<F9><a-'>"] = { function() require 'config.my.yank'.yank("'", 'n', 'W') end, "my.yank: <cWORD> to '", mode = { 'n', }, silent = true, },
  ['<F9><a-[>'] = { function() require 'config.my.yank'.yank('[', 'n', 'W') end, 'my.yank: <cWORD> to [', mode = { 'n', }, silent = true, },
  ['<F9><a-]>'] = { function() require 'config.my.yank'.yank(']', 'n', 'W') end, 'my.yank: <cWORD> to ]', mode = { 'n', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.yank'.yank('a', 'v') end, 'my.yank: sel to a', mode = { 'v', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.yank'.yank('b', 'v') end, 'my.yank: sel to b', mode = { 'v', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.yank'.yank('c', 'v') end, 'my.yank: sel to c', mode = { 'v', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.yank'.yank('d', 'v') end, 'my.yank: sel to d', mode = { 'v', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.yank'.yank('e', 'v') end, 'my.yank: sel to e', mode = { 'v', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.yank'.yank('f', 'v') end, 'my.yank: sel to f', mode = { 'v', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.yank'.yank('g', 'v') end, 'my.yank: sel to g', mode = { 'v', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.yank'.yank('h', 'v') end, 'my.yank: sel to h', mode = { 'v', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.yank'.yank('i', 'v') end, 'my.yank: sel to i', mode = { 'v', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.yank'.yank('j', 'v') end, 'my.yank: sel to j', mode = { 'v', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.yank'.yank('k', 'v') end, 'my.yank: sel to k', mode = { 'v', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.yank'.yank('l', 'v') end, 'my.yank: sel to l', mode = { 'v', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.yank'.yank('m', 'v') end, 'my.yank: sel to m', mode = { 'v', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.yank'.yank('n', 'v') end, 'my.yank: sel to n', mode = { 'v', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.yank'.yank('o', 'v') end, 'my.yank: sel to o', mode = { 'v', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.yank'.yank('p', 'v') end, 'my.yank: sel to p', mode = { 'v', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.yank'.yank('q', 'v') end, 'my.yank: sel to q', mode = { 'v', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.yank'.yank('r', 'v') end, 'my.yank: sel to r', mode = { 'v', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.yank'.yank('s', 'v') end, 'my.yank: sel to s', mode = { 'v', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.yank'.yank('t', 'v') end, 'my.yank: sel to t', mode = { 'v', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.yank'.yank('u', 'v') end, 'my.yank: sel to u', mode = { 'v', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.yank'.yank('v', 'v') end, 'my.yank: sel to v', mode = { 'v', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.yank'.yank('w', 'v') end, 'my.yank: sel to w', mode = { 'v', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.yank'.yank('x', 'v') end, 'my.yank: sel to x', mode = { 'v', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.yank'.yank('y', 'v') end, 'my.yank: sel to y', mode = { 'v', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.yank'.yank('z', 'v') end, 'my.yank: sel to z', mode = { 'v', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.yank'.yank(',', 'v') end, 'my.yank: sel to ,', mode = { 'v', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.yank'.yank('.', 'v') end, 'my.yank: sel to .', mode = { 'v', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.yank'.yank('/', 'v') end, 'my.yank: sel to /', mode = { 'v', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.yank'.yank(';', 'v') end, 'my.yank: sel to ;', mode = { 'v', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.yank'.yank("'", 'v') end, "my.yank: sel to '", mode = { 'v', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.yank'.yank('[', 'v') end, 'my.yank: sel to [', mode = { 'v', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.yank'.yank(']', 'v') end, 'my.yank: sel to ]', mode = { 'v', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.yank'.paste('a', 'i') end, 'my.yank.paste: paste from a', mode = { 'i', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.yank'.paste('b', 'i') end, 'my.yank.paste: paste from b', mode = { 'i', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.yank'.paste('c', 'i') end, 'my.yank.paste: paste from c', mode = { 'i', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.yank'.paste('d', 'i') end, 'my.yank.paste: paste from d', mode = { 'i', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.yank'.paste('e', 'i') end, 'my.yank.paste: paste from e', mode = { 'i', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.yank'.paste('f', 'i') end, 'my.yank.paste: paste from f', mode = { 'i', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.yank'.paste('g', 'i') end, 'my.yank.paste: paste from g', mode = { 'i', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.yank'.paste('h', 'i') end, 'my.yank.paste: paste from h', mode = { 'i', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.yank'.paste('i', 'i') end, 'my.yank.paste: paste from i', mode = { 'i', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.yank'.paste('j', 'i') end, 'my.yank.paste: paste from j', mode = { 'i', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.yank'.paste('k', 'i') end, 'my.yank.paste: paste from k', mode = { 'i', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.yank'.paste('l', 'i') end, 'my.yank.paste: paste from l', mode = { 'i', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.yank'.paste('m', 'i') end, 'my.yank.paste: paste from m', mode = { 'i', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.yank'.paste('n', 'i') end, 'my.yank.paste: paste from n', mode = { 'i', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.yank'.paste('o', 'i') end, 'my.yank.paste: paste from o', mode = { 'i', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.yank'.paste('p', 'i') end, 'my.yank.paste: paste from p', mode = { 'i', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.yank'.paste('q', 'i') end, 'my.yank.paste: paste from q', mode = { 'i', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.yank'.paste('r', 'i') end, 'my.yank.paste: paste from r', mode = { 'i', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.yank'.paste('s', 'i') end, 'my.yank.paste: paste from s', mode = { 'i', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.yank'.paste('t', 'i') end, 'my.yank.paste: paste from t', mode = { 'i', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.yank'.paste('u', 'i') end, 'my.yank.paste: paste from u', mode = { 'i', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.yank'.paste('v', 'i') end, 'my.yank.paste: paste from v', mode = { 'i', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.yank'.paste('w', 'i') end, 'my.yank.paste: paste from w', mode = { 'i', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.yank'.paste('x', 'i') end, 'my.yank.paste: paste from x', mode = { 'i', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.yank'.paste('y', 'i') end, 'my.yank.paste: paste from y', mode = { 'i', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.yank'.paste('z', 'i') end, 'my.yank.paste: paste from z', mode = { 'i', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.yank'.paste(',', 'i') end, 'my.yank.paste: paste from ,', mode = { 'i', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.yank'.paste('.', 'i') end, 'my.yank.paste: paste from .', mode = { 'i', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.yank'.paste('/', 'i') end, 'my.yank.paste: paste from /', mode = { 'i', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.yank'.paste(';', 'i') end, 'my.yank.paste: paste from ;', mode = { 'i', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.yank'.paste("'", 'i') end, "my.yank.paste: paste from '", mode = { 'i', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.yank'.paste('[', 'i') end, 'my.yank.paste: paste from [', mode = { 'i', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.yank'.paste(']', 'i') end, 'my.yank.paste: paste from ]', mode = { 'i', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.yank'.paste('a', 'c') end, 'my.yank.paste: paste from a', mode = { 'c', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.yank'.paste('b', 'c') end, 'my.yank.paste: paste from b', mode = { 'c', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.yank'.paste('c', 'c') end, 'my.yank.paste: paste from c', mode = { 'c', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.yank'.paste('d', 'c') end, 'my.yank.paste: paste from d', mode = { 'c', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.yank'.paste('e', 'c') end, 'my.yank.paste: paste from e', mode = { 'c', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.yank'.paste('f', 'c') end, 'my.yank.paste: paste from f', mode = { 'c', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.yank'.paste('g', 'c') end, 'my.yank.paste: paste from g', mode = { 'c', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.yank'.paste('h', 'c') end, 'my.yank.paste: paste from h', mode = { 'c', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.yank'.paste('i', 'c') end, 'my.yank.paste: paste from i', mode = { 'c', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.yank'.paste('j', 'c') end, 'my.yank.paste: paste from j', mode = { 'c', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.yank'.paste('k', 'c') end, 'my.yank.paste: paste from k', mode = { 'c', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.yank'.paste('l', 'c') end, 'my.yank.paste: paste from l', mode = { 'c', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.yank'.paste('m', 'c') end, 'my.yank.paste: paste from m', mode = { 'c', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.yank'.paste('n', 'c') end, 'my.yank.paste: paste from n', mode = { 'c', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.yank'.paste('o', 'c') end, 'my.yank.paste: paste from o', mode = { 'c', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.yank'.paste('p', 'c') end, 'my.yank.paste: paste from p', mode = { 'c', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.yank'.paste('q', 'c') end, 'my.yank.paste: paste from q', mode = { 'c', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.yank'.paste('r', 'c') end, 'my.yank.paste: paste from r', mode = { 'c', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.yank'.paste('s', 'c') end, 'my.yank.paste: paste from s', mode = { 'c', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.yank'.paste('t', 'c') end, 'my.yank.paste: paste from t', mode = { 'c', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.yank'.paste('u', 'c') end, 'my.yank.paste: paste from u', mode = { 'c', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.yank'.paste('v', 'c') end, 'my.yank.paste: paste from v', mode = { 'c', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.yank'.paste('w', 'c') end, 'my.yank.paste: paste from w', mode = { 'c', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.yank'.paste('x', 'c') end, 'my.yank.paste: paste from x', mode = { 'c', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.yank'.paste('y', 'c') end, 'my.yank.paste: paste from y', mode = { 'c', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.yank'.paste('z', 'c') end, 'my.yank.paste: paste from z', mode = { 'c', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.yank'.paste(',', 'c') end, 'my.yank.paste: paste from ,', mode = { 'c', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.yank'.paste('.', 'c') end, 'my.yank.paste: paste from .', mode = { 'c', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.yank'.paste('/', 'c') end, 'my.yank.paste: paste from /', mode = { 'c', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.yank'.paste(';', 'c') end, 'my.yank.paste: paste from ;', mode = { 'c', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.yank'.paste("'", 'c') end, "my.yank.paste: paste from '", mode = { 'c', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.yank'.paste('[', 'c') end, 'my.yank.paste: paste from [', mode = { 'c', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.yank'.paste(']', 'c') end, 'my.yank.paste: paste from ]', mode = { 'c', }, silent = true, },
}

r {
  ['<F9>a'] = { function() require 'config.my.yank'.paste('a', 't') end, 'my.yank.paste: paste from a', mode = { 't', }, silent = true, },
  ['<F9>b'] = { function() require 'config.my.yank'.paste('b', 't') end, 'my.yank.paste: paste from b', mode = { 't', }, silent = true, },
  ['<F9>c'] = { function() require 'config.my.yank'.paste('c', 't') end, 'my.yank.paste: paste from c', mode = { 't', }, silent = true, },
  ['<F9>d'] = { function() require 'config.my.yank'.paste('d', 't') end, 'my.yank.paste: paste from d', mode = { 't', }, silent = true, },
  ['<F9>e'] = { function() require 'config.my.yank'.paste('e', 't') end, 'my.yank.paste: paste from e', mode = { 't', }, silent = true, },
  ['<F9>f'] = { function() require 'config.my.yank'.paste('f', 't') end, 'my.yank.paste: paste from f', mode = { 't', }, silent = true, },
  ['<F9>g'] = { function() require 'config.my.yank'.paste('g', 't') end, 'my.yank.paste: paste from g', mode = { 't', }, silent = true, },
  ['<F9>h'] = { function() require 'config.my.yank'.paste('h', 't') end, 'my.yank.paste: paste from h', mode = { 't', }, silent = true, },
  ['<F9>i'] = { function() require 'config.my.yank'.paste('i', 't') end, 'my.yank.paste: paste from i', mode = { 't', }, silent = true, },
  ['<F9>j'] = { function() require 'config.my.yank'.paste('j', 't') end, 'my.yank.paste: paste from j', mode = { 't', }, silent = true, },
  ['<F9>k'] = { function() require 'config.my.yank'.paste('k', 't') end, 'my.yank.paste: paste from k', mode = { 't', }, silent = true, },
  ['<F9>l'] = { function() require 'config.my.yank'.paste('l', 't') end, 'my.yank.paste: paste from l', mode = { 't', }, silent = true, },
  ['<F9>m'] = { function() require 'config.my.yank'.paste('m', 't') end, 'my.yank.paste: paste from m', mode = { 't', }, silent = true, },
  ['<F9>n'] = { function() require 'config.my.yank'.paste('n', 't') end, 'my.yank.paste: paste from n', mode = { 't', }, silent = true, },
  ['<F9>o'] = { function() require 'config.my.yank'.paste('o', 't') end, 'my.yank.paste: paste from o', mode = { 't', }, silent = true, },
  ['<F9>p'] = { function() require 'config.my.yank'.paste('p', 't') end, 'my.yank.paste: paste from p', mode = { 't', }, silent = true, },
  ['<F9>q'] = { function() require 'config.my.yank'.paste('q', 't') end, 'my.yank.paste: paste from q', mode = { 't', }, silent = true, },
  ['<F9>r'] = { function() require 'config.my.yank'.paste('r', 't') end, 'my.yank.paste: paste from r', mode = { 't', }, silent = true, },
  ['<F9>s'] = { function() require 'config.my.yank'.paste('s', 't') end, 'my.yank.paste: paste from s', mode = { 't', }, silent = true, },
  ['<F9>t'] = { function() require 'config.my.yank'.paste('t', 't') end, 'my.yank.paste: paste from t', mode = { 't', }, silent = true, },
  ['<F9>u'] = { function() require 'config.my.yank'.paste('u', 't') end, 'my.yank.paste: paste from u', mode = { 't', }, silent = true, },
  ['<F9>v'] = { function() require 'config.my.yank'.paste('v', 't') end, 'my.yank.paste: paste from v', mode = { 't', }, silent = true, },
  ['<F9>w'] = { function() require 'config.my.yank'.paste('w', 't') end, 'my.yank.paste: paste from w', mode = { 't', }, silent = true, },
  ['<F9>x'] = { function() require 'config.my.yank'.paste('x', 't') end, 'my.yank.paste: paste from x', mode = { 't', }, silent = true, },
  ['<F9>y'] = { function() require 'config.my.yank'.paste('y', 't') end, 'my.yank.paste: paste from y', mode = { 't', }, silent = true, },
  ['<F9>z'] = { function() require 'config.my.yank'.paste('z', 't') end, 'my.yank.paste: paste from z', mode = { 't', }, silent = true, },
  ['<F9>,'] = { function() require 'config.my.yank'.paste(',', 't') end, 'my.yank.paste: paste from ,', mode = { 't', }, silent = true, },
  ['<F9>.'] = { function() require 'config.my.yank'.paste('.', 't') end, 'my.yank.paste: paste from .', mode = { 't', }, silent = true, },
  ['<F9>/'] = { function() require 'config.my.yank'.paste('/', 't') end, 'my.yank.paste: paste from /', mode = { 't', }, silent = true, },
  ['<F9>;'] = { function() require 'config.my.yank'.paste(';', 't') end, 'my.yank.paste: paste from ;', mode = { 't', }, silent = true, },
  ["<F9>'"] = { function() require 'config.my.yank'.paste("'", 't') end, "my.yank.paste: paste from '", mode = { 't', }, silent = true, },
  ['<F9>['] = { function() require 'config.my.yank'.paste('[', 't') end, 'my.yank.paste: paste from [', mode = { 't', }, silent = true, },
  ['<F9>]'] = { function() require 'config.my.yank'.paste(']', 't') end, 'my.yank.paste: paste from ]', mode = { 't', }, silent = true, },
}

r {
  ['<F9>A'] = { function() require 'config.my.yank'.paste('a', 'n') end, 'my.yank.paste: paste from a', mode = { 'n', 'v', }, silent = true, },
  ['<F9>B'] = { function() require 'config.my.yank'.paste('b', 'n') end, 'my.yank.paste: paste from b', mode = { 'n', 'v', }, silent = true, },
  ['<F9>C'] = { function() require 'config.my.yank'.paste('c', 'n') end, 'my.yank.paste: paste from c', mode = { 'n', 'v', }, silent = true, },
  ['<F9>D'] = { function() require 'config.my.yank'.paste('d', 'n') end, 'my.yank.paste: paste from d', mode = { 'n', 'v', }, silent = true, },
  ['<F9>E'] = { function() require 'config.my.yank'.paste('e', 'n') end, 'my.yank.paste: paste from e', mode = { 'n', 'v', }, silent = true, },
  ['<F9>F'] = { function() require 'config.my.yank'.paste('f', 'n') end, 'my.yank.paste: paste from f', mode = { 'n', 'v', }, silent = true, },
  ['<F9>G'] = { function() require 'config.my.yank'.paste('g', 'n') end, 'my.yank.paste: paste from g', mode = { 'n', 'v', }, silent = true, },
  ['<F9>H'] = { function() require 'config.my.yank'.paste('h', 'n') end, 'my.yank.paste: paste from h', mode = { 'n', 'v', }, silent = true, },
  ['<F9>I'] = { function() require 'config.my.yank'.paste('i', 'n') end, 'my.yank.paste: paste from i', mode = { 'n', 'v', }, silent = true, },
  ['<F9>J'] = { function() require 'config.my.yank'.paste('j', 'n') end, 'my.yank.paste: paste from j', mode = { 'n', 'v', }, silent = true, },
  ['<F9>K'] = { function() require 'config.my.yank'.paste('k', 'n') end, 'my.yank.paste: paste from k', mode = { 'n', 'v', }, silent = true, },
  ['<F9>L'] = { function() require 'config.my.yank'.paste('l', 'n') end, 'my.yank.paste: paste from l', mode = { 'n', 'v', }, silent = true, },
  ['<F9>M'] = { function() require 'config.my.yank'.paste('m', 'n') end, 'my.yank.paste: paste from m', mode = { 'n', 'v', }, silent = true, },
  ['<F9>N'] = { function() require 'config.my.yank'.paste('n', 'n') end, 'my.yank.paste: paste from n', mode = { 'n', 'v', }, silent = true, },
  ['<F9>O'] = { function() require 'config.my.yank'.paste('o', 'n') end, 'my.yank.paste: paste from o', mode = { 'n', 'v', }, silent = true, },
  ['<F9>P'] = { function() require 'config.my.yank'.paste('p', 'n') end, 'my.yank.paste: paste from p', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Q'] = { function() require 'config.my.yank'.paste('q', 'n') end, 'my.yank.paste: paste from q', mode = { 'n', 'v', }, silent = true, },
  ['<F9>R'] = { function() require 'config.my.yank'.paste('r', 'n') end, 'my.yank.paste: paste from r', mode = { 'n', 'v', }, silent = true, },
  ['<F9>S'] = { function() require 'config.my.yank'.paste('s', 'n') end, 'my.yank.paste: paste from s', mode = { 'n', 'v', }, silent = true, },
  ['<F9>T'] = { function() require 'config.my.yank'.paste('t', 'n') end, 'my.yank.paste: paste from t', mode = { 'n', 'v', }, silent = true, },
  ['<F9>U'] = { function() require 'config.my.yank'.paste('u', 'n') end, 'my.yank.paste: paste from u', mode = { 'n', 'v', }, silent = true, },
  ['<F9>V'] = { function() require 'config.my.yank'.paste('v', 'n') end, 'my.yank.paste: paste from v', mode = { 'n', 'v', }, silent = true, },
  ['<F9>W'] = { function() require 'config.my.yank'.paste('w', 'n') end, 'my.yank.paste: paste from w', mode = { 'n', 'v', }, silent = true, },
  ['<F9>X'] = { function() require 'config.my.yank'.paste('x', 'n') end, 'my.yank.paste: paste from x', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Y'] = { function() require 'config.my.yank'.paste('y', 'n') end, 'my.yank.paste: paste from y', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Z'] = { function() require 'config.my.yank'.paste('z', 'n') end, 'my.yank.paste: paste from z', mode = { 'n', 'v', }, silent = true, },
  ['<F9><'] = { function() require 'config.my.yank'.paste(',', 'n') end, 'my.yank.paste: paste from ,', mode = { 'n', 'v', }, silent = true, },
  ['<F9>>'] = { function() require 'config.my.yank'.paste('.', 'n') end, 'my.yank.paste: paste from .', mode = { 'n', 'v', }, silent = true, },
  ['<F9>?'] = { function() require 'config.my.yank'.paste('/', 'n') end, 'my.yank.paste: paste from /', mode = { 'n', 'v', }, silent = true, },
  ['<F9>:'] = { function() require 'config.my.yank'.paste(';', 'n') end, 'my.yank.paste: paste from ;', mode = { 'n', 'v', }, silent = true, },
  ['<F9>"'] = { function() require 'config.my.yank'.paste("'", 'n') end, "my.yank.paste: paste from '", mode = { 'n', 'v', }, silent = true, },
  ['<F9>{'] = { function() require 'config.my.yank'.paste('[', 'n') end, 'my.yank.paste: paste from [', mode = { 'n', 'v', }, silent = true, },
  ['<F9>}'] = { function() require 'config.my.yank'.paste(']', 'n') end, 'my.yank.paste: paste from ]', mode = { 'n', 'v', }, silent = true, },
}

r {
  ['<F9><c-s-a>'] = { function() require 'config.my.yank'.delete 'a' end, 'my.yank.delete: delete from a', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-b>'] = { function() require 'config.my.yank'.delete 'b' end, 'my.yank.delete: delete from b', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-c>'] = { function() require 'config.my.yank'.delete 'c' end, 'my.yank.delete: delete from c', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-d>'] = { function() require 'config.my.yank'.delete 'd' end, 'my.yank.delete: delete from d', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-e>'] = { function() require 'config.my.yank'.delete 'e' end, 'my.yank.delete: delete from e', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-f>'] = { function() require 'config.my.yank'.delete 'f' end, 'my.yank.delete: delete from f', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-g>'] = { function() require 'config.my.yank'.delete 'g' end, 'my.yank.delete: delete from g', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-h>'] = { function() require 'config.my.yank'.delete 'h' end, 'my.yank.delete: delete from h', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-i>'] = { function() require 'config.my.yank'.delete 'i' end, 'my.yank.delete: delete from i', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-j>'] = { function() require 'config.my.yank'.delete 'j' end, 'my.yank.delete: delete from j', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-k>'] = { function() require 'config.my.yank'.delete 'k' end, 'my.yank.delete: delete from k', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-l>'] = { function() require 'config.my.yank'.delete 'l' end, 'my.yank.delete: delete from l', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-m>'] = { function() require 'config.my.yank'.delete 'm' end, 'my.yank.delete: delete from m', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-n>'] = { function() require 'config.my.yank'.delete 'n' end, 'my.yank.delete: delete from n', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-o>'] = { function() require 'config.my.yank'.delete 'o' end, 'my.yank.delete: delete from o', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-p>'] = { function() require 'config.my.yank'.delete 'p' end, 'my.yank.delete: delete from p', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-q>'] = { function() require 'config.my.yank'.delete 'q' end, 'my.yank.delete: delete from q', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-r>'] = { function() require 'config.my.yank'.delete 'r' end, 'my.yank.delete: delete from r', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-s>'] = { function() require 'config.my.yank'.delete 's' end, 'my.yank.delete: delete from s', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-t>'] = { function() require 'config.my.yank'.delete 't' end, 'my.yank.delete: delete from t', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-u>'] = { function() require 'config.my.yank'.delete 'u' end, 'my.yank.delete: delete from u', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-v>'] = { function() require 'config.my.yank'.delete 'v' end, 'my.yank.delete: delete from v', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-w>'] = { function() require 'config.my.yank'.delete 'w' end, 'my.yank.delete: delete from w', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-x>'] = { function() require 'config.my.yank'.delete 'x' end, 'my.yank.delete: delete from x', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-y>'] = { function() require 'config.my.yank'.delete 'y' end, 'my.yank.delete: delete from y', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-z>'] = { function() require 'config.my.yank'.delete 'z' end, 'my.yank.delete: delete from z', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-,>'] = { function() require 'config.my.yank'.delete ',' end, 'my.yank.delete: delete from ,', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-.>'] = { function() require 'config.my.yank'.delete '.' end, 'my.yank.delete: delete from .', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-/>'] = { function() require 'config.my.yank'.delete '/' end, 'my.yank.delete: delete from /', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-;>'] = { function() require 'config.my.yank'.delete ';' end, 'my.yank.delete: delete from ;', mode = { 'n', 'v', }, silent = true, },
  ["<F9><c-s-'>"] = { function() require 'config.my.yank'.delete "'" end, "my.yank.delete: delete from '", mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-[>'] = { function() require 'config.my.yank'.delete '[' end, 'my.yank.delete: delete from [', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-]>'] = { function() require 'config.my.yank'.delete ']' end, 'my.yank.delete: delete from ]', mode = { 'n', 'v', }, silent = true, },
}

r {
  ['<F9><F1>a'] = { function() require 'config.my.yank'.clipboard 'a' end, 'my.yank.clipboard: a to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>b'] = { function() require 'config.my.yank'.clipboard 'b' end, 'my.yank.clipboard: b to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>c'] = { function() require 'config.my.yank'.clipboard 'c' end, 'my.yank.clipboard: c to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>d'] = { function() require 'config.my.yank'.clipboard 'd' end, 'my.yank.clipboard: d to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>e'] = { function() require 'config.my.yank'.clipboard 'e' end, 'my.yank.clipboard: e to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>f'] = { function() require 'config.my.yank'.clipboard 'f' end, 'my.yank.clipboard: f to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>g'] = { function() require 'config.my.yank'.clipboard 'g' end, 'my.yank.clipboard: g to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>h'] = { function() require 'config.my.yank'.clipboard 'h' end, 'my.yank.clipboard: h to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>i'] = { function() require 'config.my.yank'.clipboard 'i' end, 'my.yank.clipboard: i to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>j'] = { function() require 'config.my.yank'.clipboard 'j' end, 'my.yank.clipboard: j to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>k'] = { function() require 'config.my.yank'.clipboard 'k' end, 'my.yank.clipboard: k to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>l'] = { function() require 'config.my.yank'.clipboard 'l' end, 'my.yank.clipboard: l to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>m'] = { function() require 'config.my.yank'.clipboard 'm' end, 'my.yank.clipboard: m to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>n'] = { function() require 'config.my.yank'.clipboard 'n' end, 'my.yank.clipboard: n to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>o'] = { function() require 'config.my.yank'.clipboard 'o' end, 'my.yank.clipboard: o to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>p'] = { function() require 'config.my.yank'.clipboard 'p' end, 'my.yank.clipboard: p to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>q'] = { function() require 'config.my.yank'.clipboard 'q' end, 'my.yank.clipboard: q to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>r'] = { function() require 'config.my.yank'.clipboard 'r' end, 'my.yank.clipboard: r to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>s'] = { function() require 'config.my.yank'.clipboard 's' end, 'my.yank.clipboard: s to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>t'] = { function() require 'config.my.yank'.clipboard 't' end, 'my.yank.clipboard: t to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>u'] = { function() require 'config.my.yank'.clipboard 'u' end, 'my.yank.clipboard: u to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>v'] = { function() require 'config.my.yank'.clipboard 'v' end, 'my.yank.clipboard: v to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>w'] = { function() require 'config.my.yank'.clipboard 'w' end, 'my.yank.clipboard: w to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>x'] = { function() require 'config.my.yank'.clipboard 'x' end, 'my.yank.clipboard: x to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>y'] = { function() require 'config.my.yank'.clipboard 'y' end, 'my.yank.clipboard: y to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>z'] = { function() require 'config.my.yank'.clipboard 'z' end, 'my.yank.clipboard: z to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>,'] = { function() require 'config.my.yank'.clipboard ',' end, 'my.yank.clipboard: , to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>.'] = { function() require 'config.my.yank'.clipboard '.' end, 'my.yank.clipboard: . to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>/'] = { function() require 'config.my.yank'.clipboard '/' end, 'my.yank.clipboard: / to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>;'] = { function() require 'config.my.yank'.clipboard ';' end, 'my.yank.clipboard: ; to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ["<F9><F1>'"] = { function() require 'config.my.yank'.clipboard "'" end, "my.yank.clipboard: ' to clipboard", mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>['] = { function() require 'config.my.yank'.clipboard '[' end, 'my.yank.clipboard: [ to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>]'] = { function() require 'config.my.yank'.clipboard ']' end, 'my.yank.clipboard: ] to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
}

r {
  ['<F9><F2>'] = { function() require 'config.my.yank'.stack('n', 'w') end, 'my.yank.stack: yank <cword> to pool', mode = { 'n', }, silent = true, },
  ['<F9><F3>'] = { function() require 'config.my.yank'.stack('n', 'W') end, 'my.yank.stack: yank <cWORD> to pool', mode = { 'n', }, silent = true, },
}

r {
  ['<F9><F2>'] = { function() require 'config.my.yank'.stack('v', 'w') end, 'my.yank.stack: yank <cword> to pool', mode = { 'v', }, silent = true, },
  ['<F9><F3>'] = { function() require 'config.my.yank'.stack('v', 'W') end, 'my.yank.stack: yank <cWORD> to pool', mode = { 'v', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() require 'config.my.yank'.paste_from_stack 'n' end, 'my.yank.stack: sel paste from pool', mode = { 'n', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() require 'config.my.yank'.paste_from_stack 'v' end, 'my.yank.stack: sel paste from pool', mode = { 'v', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() require 'config.my.yank'.paste_from_stack 'i' end, 'my.yank.stack: sel paste from pool', mode = { 'i', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() require 'config.my.yank'.paste_from_stack 'c' end, 'my.yank.stack: sel paste from pool', mode = { 'c', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() require 'config.my.yank'.paste_from_stack 't' end, 'my.yank.stack: sel paste from pool', mode = { 't', }, silent = true, },
}

local end_time = vim.fn.reltimefloat(vim.fn.reltime(start_time))
local startup_time = string.format('wk.register time: %.3f ms', end_time * 1000)
print(vim.g.startup_time .. ', ' .. startup_time)

return M
