-- Copyright (c) 2024 liudepei. All Rights Reserved.
-- create at 2024/03/15 13:42:54 Friday

local M = {}

local start_time = vim.fn.reltime()

local r = require 'which-key'.register

local A = require 'config.my.yank'

r {
  ['<F9>']      = { name = 'my.yank', },
  ['<F9><F9>']  = { function() A.reg_show() end, 'show all', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9>a']     = { function() A.yank('a', 'n', 'w') end, '<cword> to a', mode = { 'n', }, silent = true, },
  ['<F9>b']     = { function() A.yank('b', 'n', 'w') end, '<cword> to b', mode = { 'n', }, silent = true, },
  ['<F9>c']     = { function() A.yank('c', 'n', 'w') end, '<cword> to c', mode = { 'n', }, silent = true, },
  ['<F9>d']     = { function() A.yank('d', 'n', 'w') end, '<cword> to d', mode = { 'n', }, silent = true, },
  ['<F9>e']     = { function() A.yank('e', 'n', 'w') end, '<cword> to e', mode = { 'n', }, silent = true, },
  ['<F9>f']     = { function() A.yank('f', 'n', 'w') end, '<cword> to f', mode = { 'n', }, silent = true, },
  ['<F9>g']     = { function() A.yank('g', 'n', 'w') end, '<cword> to g', mode = { 'n', }, silent = true, },
  ['<F9>h']     = { function() A.yank('h', 'n', 'w') end, '<cword> to h', mode = { 'n', }, silent = true, },
  ['<F9>i']     = { function() A.yank('i', 'n', 'w') end, '<cword> to i', mode = { 'n', }, silent = true, },
  ['<F9>j']     = { function() A.yank('j', 'n', 'w') end, '<cword> to j', mode = { 'n', }, silent = true, },
  ['<F9>k']     = { function() A.yank('k', 'n', 'w') end, '<cword> to k', mode = { 'n', }, silent = true, },
  ['<F9>l']     = { function() A.yank('l', 'n', 'w') end, '<cword> to l', mode = { 'n', }, silent = true, },
  ['<F9>m']     = { function() A.yank('m', 'n', 'w') end, '<cword> to m', mode = { 'n', }, silent = true, },
  ['<F9>n']     = { function() A.yank('n', 'n', 'w') end, '<cword> to n', mode = { 'n', }, silent = true, },
  ['<F9>o']     = { function() A.yank('o', 'n', 'w') end, '<cword> to o', mode = { 'n', }, silent = true, },
  ['<F9>p']     = { function() A.yank('p', 'n', 'w') end, '<cword> to p', mode = { 'n', }, silent = true, },
  ['<F9>q']     = { function() A.yank('q', 'n', 'w') end, '<cword> to q', mode = { 'n', }, silent = true, },
  ['<F9>r']     = { function() A.yank('r', 'n', 'w') end, '<cword> to r', mode = { 'n', }, silent = true, },
  ['<F9>s']     = { function() A.yank('s', 'n', 'w') end, '<cword> to s', mode = { 'n', }, silent = true, },
  ['<F9>t']     = { function() A.yank('t', 'n', 'w') end, '<cword> to t', mode = { 'n', }, silent = true, },
  ['<F9>u']     = { function() A.yank('u', 'n', 'w') end, '<cword> to u', mode = { 'n', }, silent = true, },
  ['<F9>v']     = { function() A.yank('v', 'n', 'w') end, '<cword> to v', mode = { 'n', }, silent = true, },
  ['<F9>w']     = { function() A.yank('w', 'n', 'w') end, '<cword> to w', mode = { 'n', }, silent = true, },
  ['<F9>x']     = { function() A.yank('x', 'n', 'w') end, '<cword> to x', mode = { 'n', }, silent = true, },
  ['<F9>y']     = { function() A.yank('y', 'n', 'w') end, '<cword> to y', mode = { 'n', }, silent = true, },
  ['<F9>z']     = { function() A.yank('z', 'n', 'w') end, '<cword> to z', mode = { 'n', }, silent = true, },
  ['<F9>,']     = { function() A.yank(',', 'n', 'w') end, '<cword> to ,', mode = { 'n', }, silent = true, },
  ['<F9>.']     = { function() A.yank('.', 'n', 'w') end, '<cword> to .', mode = { 'n', }, silent = true, },
  ['<F9>/']     = { function() A.yank('/', 'n', 'w') end, '<cword> to /', mode = { 'n', }, silent = true, },
  ['<F9>;']     = { function() A.yank(';', 'n', 'w') end, '<cword> to ;', mode = { 'n', }, silent = true, },
  ["<F9>'"]     = { function() A.yank("'", 'n', 'w') end, "<cword> to '", mode = { 'n', }, silent = true, },
  ['<F9>[']     = { function() A.yank('[', 'n', 'w') end, '<cword> to [', mode = { 'n', }, silent = true, },
  ['<F9>]']     = { function() A.yank(']', 'n', 'w') end, '<cword> to ]', mode = { 'n', }, silent = true, },
  ['<F9><a-a>'] = { function() A.yank('a', 'n', 'W') end, '<cWORD> to a', mode = { 'n', }, silent = true, },
  ['<F9><a-b>'] = { function() A.yank('b', 'n', 'W') end, '<cWORD> to b', mode = { 'n', }, silent = true, },
  ['<F9><a-c>'] = { function() A.yank('c', 'n', 'W') end, '<cWORD> to c', mode = { 'n', }, silent = true, },
  ['<F9><a-d>'] = { function() A.yank('d', 'n', 'W') end, '<cWORD> to d', mode = { 'n', }, silent = true, },
  ['<F9><a-e>'] = { function() A.yank('e', 'n', 'W') end, '<cWORD> to e', mode = { 'n', }, silent = true, },
  ['<F9><a-f>'] = { function() A.yank('f', 'n', 'W') end, '<cWORD> to f', mode = { 'n', }, silent = true, },
  ['<F9><a-g>'] = { function() A.yank('g', 'n', 'W') end, '<cWORD> to g', mode = { 'n', }, silent = true, },
  ['<F9><a-h>'] = { function() A.yank('h', 'n', 'W') end, '<cWORD> to h', mode = { 'n', }, silent = true, },
  ['<F9><a-i>'] = { function() A.yank('i', 'n', 'W') end, '<cWORD> to i', mode = { 'n', }, silent = true, },
  ['<F9><a-j>'] = { function() A.yank('j', 'n', 'W') end, '<cWORD> to j', mode = { 'n', }, silent = true, },
  ['<F9><a-k>'] = { function() A.yank('k', 'n', 'W') end, '<cWORD> to k', mode = { 'n', }, silent = true, },
  ['<F9><a-l>'] = { function() A.yank('l', 'n', 'W') end, '<cWORD> to l', mode = { 'n', }, silent = true, },
  ['<F9><a-m>'] = { function() A.yank('m', 'n', 'W') end, '<cWORD> to m', mode = { 'n', }, silent = true, },
  ['<F9><a-n>'] = { function() A.yank('n', 'n', 'W') end, '<cWORD> to n', mode = { 'n', }, silent = true, },
  ['<F9><a-o>'] = { function() A.yank('o', 'n', 'W') end, '<cWORD> to o', mode = { 'n', }, silent = true, },
  ['<F9><a-p>'] = { function() A.yank('p', 'n', 'W') end, '<cWORD> to p', mode = { 'n', }, silent = true, },
  ['<F9><a-q>'] = { function() A.yank('q', 'n', 'W') end, '<cWORD> to q', mode = { 'n', }, silent = true, },
  ['<F9><a-r>'] = { function() A.yank('r', 'n', 'W') end, '<cWORD> to r', mode = { 'n', }, silent = true, },
  ['<F9><a-s>'] = { function() A.yank('s', 'n', 'W') end, '<cWORD> to s', mode = { 'n', }, silent = true, },
  ['<F9><a-t>'] = { function() A.yank('t', 'n', 'W') end, '<cWORD> to t', mode = { 'n', }, silent = true, },
  ['<F9><a-u>'] = { function() A.yank('u', 'n', 'W') end, '<cWORD> to u', mode = { 'n', }, silent = true, },
  ['<F9><a-v>'] = { function() A.yank('v', 'n', 'W') end, '<cWORD> to v', mode = { 'n', }, silent = true, },
  ['<F9><a-w>'] = { function() A.yank('w', 'n', 'W') end, '<cWORD> to w', mode = { 'n', }, silent = true, },
  ['<F9><a-x>'] = { function() A.yank('x', 'n', 'W') end, '<cWORD> to x', mode = { 'n', }, silent = true, },
  ['<F9><a-y>'] = { function() A.yank('y', 'n', 'W') end, '<cWORD> to y', mode = { 'n', }, silent = true, },
  ['<F9><a-z>'] = { function() A.yank('z', 'n', 'W') end, '<cWORD> to z', mode = { 'n', }, silent = true, },
  ['<F9><a-,>'] = { function() A.yank(',', 'n', 'W') end, '<cWORD> to ,', mode = { 'n', }, silent = true, },
  ['<F9><a-.>'] = { function() A.yank('.', 'n', 'W') end, '<cWORD> to .', mode = { 'n', }, silent = true, },
  ['<F9><a-/>'] = { function() A.yank('/', 'n', 'W') end, '<cWORD> to /', mode = { 'n', }, silent = true, },
  ['<F9><a-;>'] = { function() A.yank(';', 'n', 'W') end, '<cWORD> to ;', mode = { 'n', }, silent = true, },
  ["<F9><a-'>"] = { function() A.yank("'", 'n', 'W') end, "<cWORD> to '", mode = { 'n', }, silent = true, },
  ['<F9><a-[>'] = { function() A.yank('[', 'n', 'W') end, '<cWORD> to [', mode = { 'n', }, silent = true, },
  ['<F9><a-]>'] = { function() A.yank(']', 'n', 'W') end, '<cWORD> to ]', mode = { 'n', }, silent = true, },
}

r {
  ['<F9>a'] = { function() A.yank('a', 'v') end, 'sel to a', mode = { 'v', }, silent = true, },
  ['<F9>b'] = { function() A.yank('b', 'v') end, 'sel to b', mode = { 'v', }, silent = true, },
  ['<F9>c'] = { function() A.yank('c', 'v') end, 'sel to c', mode = { 'v', }, silent = true, },
  ['<F9>d'] = { function() A.yank('d', 'v') end, 'sel to d', mode = { 'v', }, silent = true, },
  ['<F9>e'] = { function() A.yank('e', 'v') end, 'sel to e', mode = { 'v', }, silent = true, },
  ['<F9>f'] = { function() A.yank('f', 'v') end, 'sel to f', mode = { 'v', }, silent = true, },
  ['<F9>g'] = { function() A.yank('g', 'v') end, 'sel to g', mode = { 'v', }, silent = true, },
  ['<F9>h'] = { function() A.yank('h', 'v') end, 'sel to h', mode = { 'v', }, silent = true, },
  ['<F9>i'] = { function() A.yank('i', 'v') end, 'sel to i', mode = { 'v', }, silent = true, },
  ['<F9>j'] = { function() A.yank('j', 'v') end, 'sel to j', mode = { 'v', }, silent = true, },
  ['<F9>k'] = { function() A.yank('k', 'v') end, 'sel to k', mode = { 'v', }, silent = true, },
  ['<F9>l'] = { function() A.yank('l', 'v') end, 'sel to l', mode = { 'v', }, silent = true, },
  ['<F9>m'] = { function() A.yank('m', 'v') end, 'sel to m', mode = { 'v', }, silent = true, },
  ['<F9>n'] = { function() A.yank('n', 'v') end, 'sel to n', mode = { 'v', }, silent = true, },
  ['<F9>o'] = { function() A.yank('o', 'v') end, 'sel to o', mode = { 'v', }, silent = true, },
  ['<F9>p'] = { function() A.yank('p', 'v') end, 'sel to p', mode = { 'v', }, silent = true, },
  ['<F9>q'] = { function() A.yank('q', 'v') end, 'sel to q', mode = { 'v', }, silent = true, },
  ['<F9>r'] = { function() A.yank('r', 'v') end, 'sel to r', mode = { 'v', }, silent = true, },
  ['<F9>s'] = { function() A.yank('s', 'v') end, 'sel to s', mode = { 'v', }, silent = true, },
  ['<F9>t'] = { function() A.yank('t', 'v') end, 'sel to t', mode = { 'v', }, silent = true, },
  ['<F9>u'] = { function() A.yank('u', 'v') end, 'sel to u', mode = { 'v', }, silent = true, },
  ['<F9>v'] = { function() A.yank('v', 'v') end, 'sel to v', mode = { 'v', }, silent = true, },
  ['<F9>w'] = { function() A.yank('w', 'v') end, 'sel to w', mode = { 'v', }, silent = true, },
  ['<F9>x'] = { function() A.yank('x', 'v') end, 'sel to x', mode = { 'v', }, silent = true, },
  ['<F9>y'] = { function() A.yank('y', 'v') end, 'sel to y', mode = { 'v', }, silent = true, },
  ['<F9>z'] = { function() A.yank('z', 'v') end, 'sel to z', mode = { 'v', }, silent = true, },
  ['<F9>,'] = { function() A.yank(',', 'v') end, 'sel to ,', mode = { 'v', }, silent = true, },
  ['<F9>.'] = { function() A.yank('.', 'v') end, 'sel to .', mode = { 'v', }, silent = true, },
  ['<F9>/'] = { function() A.yank('/', 'v') end, 'sel to /', mode = { 'v', }, silent = true, },
  ['<F9>;'] = { function() A.yank(';', 'v') end, 'sel to ;', mode = { 'v', }, silent = true, },
  ["<F9>'"] = { function() A.yank("'", 'v') end, "sel to '", mode = { 'v', }, silent = true, },
  ['<F9>['] = { function() A.yank('[', 'v') end, 'sel to [', mode = { 'v', }, silent = true, },
  ['<F9>]'] = { function() A.yank(']', 'v') end, 'sel to ]', mode = { 'v', }, silent = true, },
}

r {
  ['<F9>a'] = { function() A.paste('a', 'i') end, 'paste from a', mode = { 'i', }, silent = true, },
  ['<F9>b'] = { function() A.paste('b', 'i') end, 'paste from b', mode = { 'i', }, silent = true, },
  ['<F9>c'] = { function() A.paste('c', 'i') end, 'paste from c', mode = { 'i', }, silent = true, },
  ['<F9>d'] = { function() A.paste('d', 'i') end, 'paste from d', mode = { 'i', }, silent = true, },
  ['<F9>e'] = { function() A.paste('e', 'i') end, 'paste from e', mode = { 'i', }, silent = true, },
  ['<F9>f'] = { function() A.paste('f', 'i') end, 'paste from f', mode = { 'i', }, silent = true, },
  ['<F9>g'] = { function() A.paste('g', 'i') end, 'paste from g', mode = { 'i', }, silent = true, },
  ['<F9>h'] = { function() A.paste('h', 'i') end, 'paste from h', mode = { 'i', }, silent = true, },
  ['<F9>i'] = { function() A.paste('i', 'i') end, 'paste from i', mode = { 'i', }, silent = true, },
  ['<F9>j'] = { function() A.paste('j', 'i') end, 'paste from j', mode = { 'i', }, silent = true, },
  ['<F9>k'] = { function() A.paste('k', 'i') end, 'paste from k', mode = { 'i', }, silent = true, },
  ['<F9>l'] = { function() A.paste('l', 'i') end, 'paste from l', mode = { 'i', }, silent = true, },
  ['<F9>m'] = { function() A.paste('m', 'i') end, 'paste from m', mode = { 'i', }, silent = true, },
  ['<F9>n'] = { function() A.paste('n', 'i') end, 'paste from n', mode = { 'i', }, silent = true, },
  ['<F9>o'] = { function() A.paste('o', 'i') end, 'paste from o', mode = { 'i', }, silent = true, },
  ['<F9>p'] = { function() A.paste('p', 'i') end, 'paste from p', mode = { 'i', }, silent = true, },
  ['<F9>q'] = { function() A.paste('q', 'i') end, 'paste from q', mode = { 'i', }, silent = true, },
  ['<F9>r'] = { function() A.paste('r', 'i') end, 'paste from r', mode = { 'i', }, silent = true, },
  ['<F9>s'] = { function() A.paste('s', 'i') end, 'paste from s', mode = { 'i', }, silent = true, },
  ['<F9>t'] = { function() A.paste('t', 'i') end, 'paste from t', mode = { 'i', }, silent = true, },
  ['<F9>u'] = { function() A.paste('u', 'i') end, 'paste from u', mode = { 'i', }, silent = true, },
  ['<F9>v'] = { function() A.paste('v', 'i') end, 'paste from v', mode = { 'i', }, silent = true, },
  ['<F9>w'] = { function() A.paste('w', 'i') end, 'paste from w', mode = { 'i', }, silent = true, },
  ['<F9>x'] = { function() A.paste('x', 'i') end, 'paste from x', mode = { 'i', }, silent = true, },
  ['<F9>y'] = { function() A.paste('y', 'i') end, 'paste from y', mode = { 'i', }, silent = true, },
  ['<F9>z'] = { function() A.paste('z', 'i') end, 'paste from z', mode = { 'i', }, silent = true, },
  ['<F9>,'] = { function() A.paste(',', 'i') end, 'paste from ,', mode = { 'i', }, silent = true, },
  ['<F9>.'] = { function() A.paste('.', 'i') end, 'paste from .', mode = { 'i', }, silent = true, },
  ['<F9>/'] = { function() A.paste('/', 'i') end, 'paste from /', mode = { 'i', }, silent = true, },
  ['<F9>;'] = { function() A.paste(';', 'i') end, 'paste from ;', mode = { 'i', }, silent = true, },
  ["<F9>'"] = { function() A.paste("'", 'i') end, "paste from '", mode = { 'i', }, silent = true, },
  ['<F9>['] = { function() A.paste('[', 'i') end, 'paste from [', mode = { 'i', }, silent = true, },
  ['<F9>]'] = { function() A.paste(']', 'i') end, 'paste from ]', mode = { 'i', }, silent = true, },
}

r {
  ['<F9>a'] = { function() A.paste('a', 'c') end, 'paste from a', mode = { 'c', }, silent = true, },
  ['<F9>b'] = { function() A.paste('b', 'c') end, 'paste from b', mode = { 'c', }, silent = true, },
  ['<F9>c'] = { function() A.paste('c', 'c') end, 'paste from c', mode = { 'c', }, silent = true, },
  ['<F9>d'] = { function() A.paste('d', 'c') end, 'paste from d', mode = { 'c', }, silent = true, },
  ['<F9>e'] = { function() A.paste('e', 'c') end, 'paste from e', mode = { 'c', }, silent = true, },
  ['<F9>f'] = { function() A.paste('f', 'c') end, 'paste from f', mode = { 'c', }, silent = true, },
  ['<F9>g'] = { function() A.paste('g', 'c') end, 'paste from g', mode = { 'c', }, silent = true, },
  ['<F9>h'] = { function() A.paste('h', 'c') end, 'paste from h', mode = { 'c', }, silent = true, },
  ['<F9>i'] = { function() A.paste('i', 'c') end, 'paste from i', mode = { 'c', }, silent = true, },
  ['<F9>j'] = { function() A.paste('j', 'c') end, 'paste from j', mode = { 'c', }, silent = true, },
  ['<F9>k'] = { function() A.paste('k', 'c') end, 'paste from k', mode = { 'c', }, silent = true, },
  ['<F9>l'] = { function() A.paste('l', 'c') end, 'paste from l', mode = { 'c', }, silent = true, },
  ['<F9>m'] = { function() A.paste('m', 'c') end, 'paste from m', mode = { 'c', }, silent = true, },
  ['<F9>n'] = { function() A.paste('n', 'c') end, 'paste from n', mode = { 'c', }, silent = true, },
  ['<F9>o'] = { function() A.paste('o', 'c') end, 'paste from o', mode = { 'c', }, silent = true, },
  ['<F9>p'] = { function() A.paste('p', 'c') end, 'paste from p', mode = { 'c', }, silent = true, },
  ['<F9>q'] = { function() A.paste('q', 'c') end, 'paste from q', mode = { 'c', }, silent = true, },
  ['<F9>r'] = { function() A.paste('r', 'c') end, 'paste from r', mode = { 'c', }, silent = true, },
  ['<F9>s'] = { function() A.paste('s', 'c') end, 'paste from s', mode = { 'c', }, silent = true, },
  ['<F9>t'] = { function() A.paste('t', 'c') end, 'paste from t', mode = { 'c', }, silent = true, },
  ['<F9>u'] = { function() A.paste('u', 'c') end, 'paste from u', mode = { 'c', }, silent = true, },
  ['<F9>v'] = { function() A.paste('v', 'c') end, 'paste from v', mode = { 'c', }, silent = true, },
  ['<F9>w'] = { function() A.paste('w', 'c') end, 'paste from w', mode = { 'c', }, silent = true, },
  ['<F9>x'] = { function() A.paste('x', 'c') end, 'paste from x', mode = { 'c', }, silent = true, },
  ['<F9>y'] = { function() A.paste('y', 'c') end, 'paste from y', mode = { 'c', }, silent = true, },
  ['<F9>z'] = { function() A.paste('z', 'c') end, 'paste from z', mode = { 'c', }, silent = true, },
  ['<F9>,'] = { function() A.paste(',', 'c') end, 'paste from ,', mode = { 'c', }, silent = true, },
  ['<F9>.'] = { function() A.paste('.', 'c') end, 'paste from .', mode = { 'c', }, silent = true, },
  ['<F9>/'] = { function() A.paste('/', 'c') end, 'paste from /', mode = { 'c', }, silent = true, },
  ['<F9>;'] = { function() A.paste(';', 'c') end, 'paste from ;', mode = { 'c', }, silent = true, },
  ["<F9>'"] = { function() A.paste("'", 'c') end, "paste from '", mode = { 'c', }, silent = true, },
  ['<F9>['] = { function() A.paste('[', 'c') end, 'paste from [', mode = { 'c', }, silent = true, },
  ['<F9>]'] = { function() A.paste(']', 'c') end, 'paste from ]', mode = { 'c', }, silent = true, },
}

r {
  ['<F9>a'] = { function() A.paste('a', 't') end, 'paste from a', mode = { 't', }, silent = true, },
  ['<F9>b'] = { function() A.paste('b', 't') end, 'paste from b', mode = { 't', }, silent = true, },
  ['<F9>c'] = { function() A.paste('c', 't') end, 'paste from c', mode = { 't', }, silent = true, },
  ['<F9>d'] = { function() A.paste('d', 't') end, 'paste from d', mode = { 't', }, silent = true, },
  ['<F9>e'] = { function() A.paste('e', 't') end, 'paste from e', mode = { 't', }, silent = true, },
  ['<F9>f'] = { function() A.paste('f', 't') end, 'paste from f', mode = { 't', }, silent = true, },
  ['<F9>g'] = { function() A.paste('g', 't') end, 'paste from g', mode = { 't', }, silent = true, },
  ['<F9>h'] = { function() A.paste('h', 't') end, 'paste from h', mode = { 't', }, silent = true, },
  ['<F9>i'] = { function() A.paste('i', 't') end, 'paste from i', mode = { 't', }, silent = true, },
  ['<F9>j'] = { function() A.paste('j', 't') end, 'paste from j', mode = { 't', }, silent = true, },
  ['<F9>k'] = { function() A.paste('k', 't') end, 'paste from k', mode = { 't', }, silent = true, },
  ['<F9>l'] = { function() A.paste('l', 't') end, 'paste from l', mode = { 't', }, silent = true, },
  ['<F9>m'] = { function() A.paste('m', 't') end, 'paste from m', mode = { 't', }, silent = true, },
  ['<F9>n'] = { function() A.paste('n', 't') end, 'paste from n', mode = { 't', }, silent = true, },
  ['<F9>o'] = { function() A.paste('o', 't') end, 'paste from o', mode = { 't', }, silent = true, },
  ['<F9>p'] = { function() A.paste('p', 't') end, 'paste from p', mode = { 't', }, silent = true, },
  ['<F9>q'] = { function() A.paste('q', 't') end, 'paste from q', mode = { 't', }, silent = true, },
  ['<F9>r'] = { function() A.paste('r', 't') end, 'paste from r', mode = { 't', }, silent = true, },
  ['<F9>s'] = { function() A.paste('s', 't') end, 'paste from s', mode = { 't', }, silent = true, },
  ['<F9>t'] = { function() A.paste('t', 't') end, 'paste from t', mode = { 't', }, silent = true, },
  ['<F9>u'] = { function() A.paste('u', 't') end, 'paste from u', mode = { 't', }, silent = true, },
  ['<F9>v'] = { function() A.paste('v', 't') end, 'paste from v', mode = { 't', }, silent = true, },
  ['<F9>w'] = { function() A.paste('w', 't') end, 'paste from w', mode = { 't', }, silent = true, },
  ['<F9>x'] = { function() A.paste('x', 't') end, 'paste from x', mode = { 't', }, silent = true, },
  ['<F9>y'] = { function() A.paste('y', 't') end, 'paste from y', mode = { 't', }, silent = true, },
  ['<F9>z'] = { function() A.paste('z', 't') end, 'paste from z', mode = { 't', }, silent = true, },
  ['<F9>,'] = { function() A.paste(',', 't') end, 'paste from ,', mode = { 't', }, silent = true, },
  ['<F9>.'] = { function() A.paste('.', 't') end, 'paste from .', mode = { 't', }, silent = true, },
  ['<F9>/'] = { function() A.paste('/', 't') end, 'paste from /', mode = { 't', }, silent = true, },
  ['<F9>;'] = { function() A.paste(';', 't') end, 'paste from ;', mode = { 't', }, silent = true, },
  ["<F9>'"] = { function() A.paste("'", 't') end, "paste from '", mode = { 't', }, silent = true, },
  ['<F9>['] = { function() A.paste('[', 't') end, 'paste from [', mode = { 't', }, silent = true, },
  ['<F9>]'] = { function() A.paste(']', 't') end, 'paste from ]', mode = { 't', }, silent = true, },
}

r {
  ['<F9>A'] = { function() A.paste('a', 'n') end, 'paste from a', mode = { 'n', 'v', }, silent = true, },
  ['<F9>B'] = { function() A.paste('b', 'n') end, 'paste from b', mode = { 'n', 'v', }, silent = true, },
  ['<F9>C'] = { function() A.paste('c', 'n') end, 'paste from c', mode = { 'n', 'v', }, silent = true, },
  ['<F9>D'] = { function() A.paste('d', 'n') end, 'paste from d', mode = { 'n', 'v', }, silent = true, },
  ['<F9>E'] = { function() A.paste('e', 'n') end, 'paste from e', mode = { 'n', 'v', }, silent = true, },
  ['<F9>F'] = { function() A.paste('f', 'n') end, 'paste from f', mode = { 'n', 'v', }, silent = true, },
  ['<F9>G'] = { function() A.paste('g', 'n') end, 'paste from g', mode = { 'n', 'v', }, silent = true, },
  ['<F9>H'] = { function() A.paste('h', 'n') end, 'paste from h', mode = { 'n', 'v', }, silent = true, },
  ['<F9>I'] = { function() A.paste('i', 'n') end, 'paste from i', mode = { 'n', 'v', }, silent = true, },
  ['<F9>J'] = { function() A.paste('j', 'n') end, 'paste from j', mode = { 'n', 'v', }, silent = true, },
  ['<F9>K'] = { function() A.paste('k', 'n') end, 'paste from k', mode = { 'n', 'v', }, silent = true, },
  ['<F9>L'] = { function() A.paste('l', 'n') end, 'paste from l', mode = { 'n', 'v', }, silent = true, },
  ['<F9>M'] = { function() A.paste('m', 'n') end, 'paste from m', mode = { 'n', 'v', }, silent = true, },
  ['<F9>N'] = { function() A.paste('n', 'n') end, 'paste from n', mode = { 'n', 'v', }, silent = true, },
  ['<F9>O'] = { function() A.paste('o', 'n') end, 'paste from o', mode = { 'n', 'v', }, silent = true, },
  ['<F9>P'] = { function() A.paste('p', 'n') end, 'paste from p', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Q'] = { function() A.paste('q', 'n') end, 'paste from q', mode = { 'n', 'v', }, silent = true, },
  ['<F9>R'] = { function() A.paste('r', 'n') end, 'paste from r', mode = { 'n', 'v', }, silent = true, },
  ['<F9>S'] = { function() A.paste('s', 'n') end, 'paste from s', mode = { 'n', 'v', }, silent = true, },
  ['<F9>T'] = { function() A.paste('t', 'n') end, 'paste from t', mode = { 'n', 'v', }, silent = true, },
  ['<F9>U'] = { function() A.paste('u', 'n') end, 'paste from u', mode = { 'n', 'v', }, silent = true, },
  ['<F9>V'] = { function() A.paste('v', 'n') end, 'paste from v', mode = { 'n', 'v', }, silent = true, },
  ['<F9>W'] = { function() A.paste('w', 'n') end, 'paste from w', mode = { 'n', 'v', }, silent = true, },
  ['<F9>X'] = { function() A.paste('x', 'n') end, 'paste from x', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Y'] = { function() A.paste('y', 'n') end, 'paste from y', mode = { 'n', 'v', }, silent = true, },
  ['<F9>Z'] = { function() A.paste('z', 'n') end, 'paste from z', mode = { 'n', 'v', }, silent = true, },
  ['<F9><'] = { function() A.paste(',', 'n') end, 'paste from ,', mode = { 'n', 'v', }, silent = true, },
  ['<F9>>'] = { function() A.paste('.', 'n') end, 'paste from .', mode = { 'n', 'v', }, silent = true, },
  ['<F9>?'] = { function() A.paste('/', 'n') end, 'paste from /', mode = { 'n', 'v', }, silent = true, },
  ['<F9>:'] = { function() A.paste(';', 'n') end, 'paste from ;', mode = { 'n', 'v', }, silent = true, },
  ['<F9>"'] = { function() A.paste("'", 'n') end, "paste from '", mode = { 'n', 'v', }, silent = true, },
  ['<F9>{'] = { function() A.paste('[', 'n') end, 'paste from [', mode = { 'n', 'v', }, silent = true, },
  ['<F9>}'] = { function() A.paste(']', 'n') end, 'paste from ]', mode = { 'n', 'v', }, silent = true, },
}

r {
  ['<F9><c-s-a>'] = { function() A.delete 'a' end, 'delete from a', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-b>'] = { function() A.delete 'b' end, 'delete from b', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-c>'] = { function() A.delete 'c' end, 'delete from c', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-d>'] = { function() A.delete 'd' end, 'delete from d', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-e>'] = { function() A.delete 'e' end, 'delete from e', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-f>'] = { function() A.delete 'f' end, 'delete from f', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-g>'] = { function() A.delete 'g' end, 'delete from g', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-h>'] = { function() A.delete 'h' end, 'delete from h', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-i>'] = { function() A.delete 'i' end, 'delete from i', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-j>'] = { function() A.delete 'j' end, 'delete from j', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-k>'] = { function() A.delete 'k' end, 'delete from k', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-l>'] = { function() A.delete 'l' end, 'delete from l', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-m>'] = { function() A.delete 'm' end, 'delete from m', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-n>'] = { function() A.delete 'n' end, 'delete from n', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-o>'] = { function() A.delete 'o' end, 'delete from o', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-p>'] = { function() A.delete 'p' end, 'delete from p', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-q>'] = { function() A.delete 'q' end, 'delete from q', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-r>'] = { function() A.delete 'r' end, 'delete from r', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-s>'] = { function() A.delete 's' end, 'delete from s', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-t>'] = { function() A.delete 't' end, 'delete from t', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-u>'] = { function() A.delete 'u' end, 'delete from u', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-v>'] = { function() A.delete 'v' end, 'delete from v', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-w>'] = { function() A.delete 'w' end, 'delete from w', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-x>'] = { function() A.delete 'x' end, 'delete from x', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-y>'] = { function() A.delete 'y' end, 'delete from y', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-z>'] = { function() A.delete 'z' end, 'delete from z', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-,>'] = { function() A.delete ',' end, 'delete from ,', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-.>'] = { function() A.delete '.' end, 'delete from .', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-/>'] = { function() A.delete '/' end, 'delete from /', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-;>'] = { function() A.delete ';' end, 'delete from ;', mode = { 'n', 'v', }, silent = true, },
  ["<F9><c-s-'>"] = { function() A.delete "'" end, "delete from '", mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-[>'] = { function() A.delete '[' end, 'delete from [', mode = { 'n', 'v', }, silent = true, },
  ['<F9><c-s-]>'] = { function() A.delete ']' end, 'delete from ]', mode = { 'n', 'v', }, silent = true, },
}

r {
  ['<F9><F1>'] = { name = '+my.yank.clipboard', },
  ['<F9><F1>a'] = { function() A.clipboard 'a' end, 'a to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>b'] = { function() A.clipboard 'b' end, 'b to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>c'] = { function() A.clipboard 'c' end, 'c to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>d'] = { function() A.clipboard 'd' end, 'd to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>e'] = { function() A.clipboard 'e' end, 'e to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>f'] = { function() A.clipboard 'f' end, 'f to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>g'] = { function() A.clipboard 'g' end, 'g to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>h'] = { function() A.clipboard 'h' end, 'h to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>i'] = { function() A.clipboard 'i' end, 'i to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>j'] = { function() A.clipboard 'j' end, 'j to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>k'] = { function() A.clipboard 'k' end, 'k to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>l'] = { function() A.clipboard 'l' end, 'l to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>m'] = { function() A.clipboard 'm' end, 'm to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>n'] = { function() A.clipboard 'n' end, 'n to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>o'] = { function() A.clipboard 'o' end, 'o to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>p'] = { function() A.clipboard 'p' end, 'p to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>q'] = { function() A.clipboard 'q' end, 'q to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>r'] = { function() A.clipboard 'r' end, 'r to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>s'] = { function() A.clipboard 's' end, 's to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>t'] = { function() A.clipboard 't' end, 't to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>u'] = { function() A.clipboard 'u' end, 'u to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>v'] = { function() A.clipboard 'v' end, 'v to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>w'] = { function() A.clipboard 'w' end, 'w to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>x'] = { function() A.clipboard 'x' end, 'x to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>y'] = { function() A.clipboard 'y' end, 'y to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>z'] = { function() A.clipboard 'z' end, 'z to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>,'] = { function() A.clipboard ',' end, ', to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>.'] = { function() A.clipboard '.' end, '. to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>/'] = { function() A.clipboard '/' end, '/ to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>;'] = { function() A.clipboard ';' end, '; to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ["<F9><F1>'"] = { function() A.clipboard "'" end, "' to clipboard", mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>['] = { function() A.clipboard '[' end, '[ to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
  ['<F9><F1>]'] = { function() A.clipboard ']' end, '] to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
}

r {
  ['<F9><F2>'] = { function() A.stack('n', 'w') end, 'yank <cword> to pool', mode = { 'n', }, silent = true, },
  ['<F9><F3>'] = { function() A.stack('n', 'W') end, 'yank <cWORD> to pool', mode = { 'n', }, silent = true, },
}

r {
  ['<F9><F2>'] = { function() A.stack('v', 'w') end, 'yank <cword> to pool', mode = { 'v', }, silent = true, },
  ['<F9><F3>'] = { function() A.stack('v', 'W') end, 'yank <cWORD> to pool', mode = { 'v', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() A.paste_from_stack 'n' end, 'sel paste from pool', mode = { 'n', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() A.paste_from_stack 'v' end, 'sel paste from pool', mode = { 'v', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() A.paste_from_stack 'i' end, 'sel paste from pool', mode = { 'i', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() A.paste_from_stack 'c' end, 'sel paste from pool', mode = { 'c', }, silent = true, },
}

r {
  ['<F9><F4>'] = { function() A.paste_from_stack 't' end, 'sel paste from pool', mode = { 't', }, silent = true, },
}

r {
  ['<F9><F1><F1>'] = { function() A.clipboard_from_pool() end, 'sel from pool to clipboard', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
}

r {
  ['<F9><c-F4>'] = { function() A.delete_pool() end, 'delete pool', mode = { 'n', 'v', 'i', 'c', 't', }, silent = true, },
}

local end_time = vim.fn.reltimefloat(vim.fn.reltime(start_time))
Notify(string.format('yank: %.3f ms', end_time * 1000))

return M
